### ISSUE TITLE
Proper packing

### ISSUE THREAD

**Issue by jledet** [libcsp/libcsp#1]
We're approaching CSP version 1.0, so we should start focusing on proper packing of the library. We need to:
- ~~Go through the documentation. Make sure everything is in doxygen format~~
- ~~Create README, INSTALL and LICENSE files~~
- ~~Make a good makefile for compiling the library without Eclipse. Could the GNU Autotools be used?~~
- ~~Create an examples dir with a running example~~

**Comment by jledet** [comment]
~~We'll need to add a default config file to the package as well.~~

**Comment by jledet** [comment]
We should also add a doxyfile and create a ./waf doc target for creating the documentation

**Comment by johandc** [comment]
Added simple.c to /examples

compile with ./waf configure --enable-examples build

Run with ./build/simple og ./build/simple -v to enable verbose output

**Comment by johandc** [comment]
All tasks completed.
