### ISSUE TITLE
1.0-RC1 Testing

### ISSUE THREAD

**Issue by johandc** [libcsp/libcsp#10]
Make a list of features and do systematic test of the release candidate.
- Services:
  - CSP_PING
  - CSP_PS
  - CSP_MEMFREE
  - CSP_REBOOT
  - CSP_BUF_FREE
  - CSP_UPTIME
  - CSP_STATS
- Features:
  - RDP
  - CRC32
  - HMAC
  - XTEA
- Platforms:
  - FreeRTOS
  - Posix
- Interfaces:
  - Loopback

**Comment by jledet** [comment]
Test on both big and little endian systems

**Comment by jledet** [comment]
...and new CSP CMP ident command

**Comment by jledet** [comment]
...and CAN interfaces

**Comment by jledet** [comment]
A tested version 1.0 was committed in 89cfddac. Yay!
