### ISSUE TITLE
Does RDP mode handle duplicate received packets correctly?

### ISSUE THREAD

**Issue by battlesnake** [libcsp/libcsp#107]
If a certain packet in the sequence is received twice (e.g. multiple dumb ground stations with no CSP IDs themselves, which just pass packets), does RDP handle this correctly on the receiving side?

**Comment by johandc** [comment]
Yes RDP does. But if you use a non RDP connection, you should enable packet-level deduplication at compile time by setting CSP_DEDUP = true.

**Comment by battlesnake** [comment]
Thanks.  Closing.
