### ISSUE TITLE
Add I2C and KISS interfaces

### ISSUE THREAD

**Issue by jledet** [libcsp/libcsp#11]
The interfaces for I2C and KISS are currently kept in the closed GomSpace repositories. We should clean them up and release them to public use for v1.1

**Comment by jledet** [comment]
A preliminary version of the KISS interface was added in f04c5467. The USART API still needs to be documented somewhere.

**Comment by jledet** [comment]
Remember the corresponding issue in GomSpace/libio when closing this

**Comment by johandc** [comment]
completed
