### ISSUE TITLE
Add Windows and Mac OS X support

### ISSUE THREAD

**Issue by jledet** [libcsp/libcsp#12]
Add support for windows. Dan Erik Holmstrøm has added preliminary windows support here https://github.com/danerik/libcsp, but we still need e.g. a serial port driver.

While we're at it, we might as well try to add Mac OS X support. The current posix branch doesn't compile because OS X lacks the pthread semaphore/mutex realtime extensions. We can probably find a workaround.

**Comment by jledet** [comment]
The PCAN-USB dongle also has a set of windows drivers (http://goo.gl/rZJ2P) so we can create a CAN interface for windows as well.

**Comment by johandc** [comment]
Merged windows support into master issue #13

**Comment by jledet** [comment]
Windows and OSX support is available in master
