### ISSUE TITLE
INSTALL.rst specifies a --with-freertos=PATH. Option, when no option exists.

### ISSUE THREAD

**Issue by EvanGee** [libcsp/libcsp#128]
When compiling for FreeRTOS, the path to the FreeRTOS header files must be specified with --with-freertos=PATH.

this option doesn't appear to exist in the waf script? Am I missing something?

**Comment by perwulff** [comment]
hi,
The option listed in INSTALL.rst is wrong. Instead of
 --with-freertos=PATH
it should be
--includes=PATH.

**Comment by EvanGee** [comment]
Thanks man!
