### ISSUE TITLE
Automatic host discovery/multiple routes

### ISSUE THREAD

**Issue by jledet** [libcsp/libcsp#14]
Some kind of automatic discovery of other hosts on the bus would be nice. Maybe even with gateway announcements from the radio(s)...

**Comment by johandc** [comment]
http://en.wikipedia.org/wiki/Distance-vector_routing_protocol
http://en.wikipedia.org/wiki/Routing_Information_Protocol

RIP ser meget passende ud.

**Comment by jledet** [comment]
This would also allow redundant radio links or redundant buses in the spacecraft.

**Comment by johandc** [comment]
Or implement source routing by caching discovered routes in every hop.

**Comment by jledet** [comment]
This is still a good idea! Let's do it for 2.0.

**Comment by johandc** [comment]
Host discovery has not been made possible with CSP 2.0 L2 broadcast.
Redundant radio links is possible with PROMISC mode on CAN bus.
I'm closing this now.
