### ISSUE TITLE
Possible bug in ACK transmission when using RDP protocol

### ISSUE THREAD

**Issue by marcobergamin** [libcsp/libcsp#158]
Hello,

Using CSP v1.5.16 from Gomspace repository I may have found a problem in the ACK transmission mechanism.

The problem appears when the library is compiled with this flag
```
--with-conn-queue-length=X
```
And a RDP window size Y has a value such that ```2 * Y > X```.

In the header file ```csp_types.h``` we have
```cpp
#define CSP_RX_QUEUE_LENGTH		CSP_CONN_QUEUE_LENGTH
```
And in file ```csp_rdp.c``` the following function
```cpp
int csp_rdp_check_ack(csp_conn_t * conn) {

	/* Check all RX queues for spare capacity */
	int prio, avail = 1;
	for (prio = 0; prio < CSP_RX_QUEUES; prio++) {
		if (CSP_RX_QUEUE_LENGTH - csp_queue_size(conn->rx_queue[prio]) <= 2 * (int32_t)conn->rdp.window_size) {
			avail = 0;
			break;
		}
	}

	/* If more space available, only send after ack timeout or immediately if delay_acks is zero */
	if (avail && csp_rdp_should_ack(conn))
		csp_rdp_send_cmp(conn, NULL, RDP_ACK, conn->rdp.snd_nxt, conn->rdp.rcv_cur);

	return CSP_ERR_NONE;

}
```
What I have observed is that the ```avail``` variable is always set to zero and the function ```csp_rdp_should_ack(conn)``` is never called. The ACK packet is sent only after the ACK timeout set in the RDP options. Is it supposed to work like this?

Thanks.
Marco

**Comment by johandc** [comment]
Fixed in latest development branch
