### ISSUE TITLE
Windows USART should add fd to ctx?

### ISSUE THREAD

**Issue by arrooney** [libcsp/libcsp#159]
I've been trying to get CSP to send to my COM port device in Windows, upon inspection of my error, I was getting error value 6 from the call to Windows' `WriteFile()` function which means the fd value is bad.

On closer inspection the fd value the `csp_usart_write` function is getting a Null (all zeros) value of fd, despite the call to `CreateFile` not throwing any errors.

Should there not be something along the lines of 
```
*return_fd = fd;
```
In `csp_usart_open`? Since it seems like the device file is opened, configured, and then never referenced again (except for by the rx thread). Am I missing something?

https://github.com/libcsp/libcsp/blob/87006959696c78f70535ab382b0bcd4cb5a6558d/src/drivers/usart/usart_windows.c#L137

**Comment by johandc** [comment]
Correct.

That must have been a regression in the latest version 1.6, where driver initialization was significantly updated.

If you compare to the uart_linux.c, we also update the return_fd before the end of the init call

if (return_fd) {
      *return_fd = fd;
}
