### ISSUE TITLE
Better way of passing CAN ID and Mask to the driver

### ISSUE THREAD

**Issue by 9a3eedi** [libcsp/libcsp#168]
In my project, I had previously written a custom CAN driver for CSP 1.4 for an embedded FreeRTOS system, I had to implement a few functions, one of which was can_init. CSP would call this function to initialize the CAN device, and passes in a ready-made CAN ID and a mask, and I can use that to set up my CAN device. This was straightforward to work with.

I decided to upgrade my project to CSP 1.6. With CSP 1.6, I had to rewrite the driver code to workwith the new way of doing things. Looking at the socketcan driver code as an example, it seems that the driver code needs to figure out on its own what the CAN address and mask should be. This is what's found in the socketcan code:

`
		struct can_filter filter = {.can_id = CFP_MAKE_DST(csp_get_address()),
						.can_mask = CFP_MAKE_DST((1 << CFP_HOST_SIZE) - 1)};`

This is a minor thing.. but in my opinion it's not as straightforward for the driver developer as the previous method. It requires the driver to understand too much about the CFP macros. If I didn't have the socketcan code as an example, it would've been very difficult for me to figure that out. It would be better if there were at least some cleaner way of defining to the driver what the address and mask should be, as it were before. 

Just feedback from a custom driver developer.

**Comment by johandc** [comment]
You are right, this information should come from the layer above the can driver. And in fact, in v2.0 where we changed the CFP format, there is now an ugly if-case inside our can_driver_init code, trying to figure out whether to generate a version 1 or 2 CFP mask. I would like to see this change, and perhaps include more drivers into the library as examples. For example include popular embedded frameworks, such as atmel start, or STM embedded libraries. What platform did you write a driver for?

**Comment by 9a3eedi** [comment]
I was developing a driver for an MCP2515 being driven by SPI by a Cortex M3 (EFM32GG)

Interesting, I wasn't aware there are now two versions of CFP. Perhaps I should do more reading.

**Comment by johandc** [comment]
We need this for broadcast to work too.

**Comment by johandc** [comment]
I will upload an example can driver to contrib. Which should be helpfull for driver development.
