### ISSUE TITLE
csp_sfp_send doesn't unset CSP_FFRAG when it's done

### ISSUE THREAD

**Issue by 9a3eedi** [libcsp/libcsp#172]
In CSP 1.6, when performing an SFP send with csp_sfp_send_own_memcpy(), the code sets csp_conn_t's idout flags with the CSP_FFRAG flag before sending the packets. After it is done, it does not unset it from the connection, so any non-SFP packets sent on this connection will be received with CSP_FFRAG enabled.

I'm not sure if this is a bug or intended behaviour. I only found this out after attempting to differentiate between SFP packets and regular packets on the receiving side via the packet's flag. Shouldn't the flag only be enabled for SFP (and other fragmented packet protocols)?

**Comment by johandc** [comment]
A connection cannot be used without SFP after using SFP. You should create a new connection with new flags.
