### ISSUE TITLE
surprise coupling between server and client, leads to bootstrap issue

### ISSUE THREAD

**Issue by schaefer01** [libcsp/libcsp#175]
HI, I'm trying to embed the client but am running into a pull-yourself-up-by-your-own-boostraps  problem.

Per your example, csp_server_client.c, setting the clock is only done in the server but not the client but because setting the clock is an OS feature and the server and client are on the same processor, 
the client clock is set when the server clock is set (and both are automatically set by the OS).
Once you decouple the client from the server, an embedded client doesn't know what time it is, and there is no "call" to set the clock inside the libcsp code.

The calliing sequence: -> src/csp_service_handler.c -> do_cmp_clock -> csp_cmp_handler -> csp_service_handler

but csp_service_handler is only called in the server, so the server has no idea and no command to determain what the client's clock is.

Any help?

**Comment by johandc** [comment]
Here is our code to set and get the clock.

If you specify -1, it will set the local system time to the remote node. If you set it to zero, it will get the time without setting it, and if you specify a positive number the time will be set to that value.

static int slash_csp_cmp_time(struct slash *slash)
{
	if ((slash->argc < 3) || (slash->argc > 4))
		return SLASH_EUSAGE;

	unsigned int node = atoi(slash->argv[1]);
	int timestamp = atoi(slash->argv[2]);
	unsigned int timeout = 1000;
	if (slash->argc > 3)
		timeout = atoi(slash->argv[3]);

	struct csp_cmp_message message;

	csp_timestamp_t localtime;
	clock_get_time(&localtime);

	if (timestamp == -1) {
		message.clock.tv_sec = csp_hton32(localtime.tv_sec);
		message.clock.tv_nsec = csp_hton32(localtime.tv_nsec);
	} else {
		message.clock.tv_sec = csp_hton32(timestamp);
		message.clock.tv_nsec = csp_hton32(0);
	}

	if (csp_cmp_clock(node, timeout, &message) != CSP_ERR_NONE) {
		printf("No response\n");
		return SLASH_EINVAL;
	}

	message.clock.tv_sec = csp_ntoh32(message.clock.tv_sec);
	message.clock.tv_nsec = csp_ntoh32(message.clock.tv_nsec);

	int64_t remote_time_ns = message.clock.tv_sec * 1E9 + message.clock.tv_nsec;
	int64_t local_time_ns = localtime.tv_sec * 1E9 + localtime.tv_nsec;

	printf("Remote time is %"PRIu32".%09"PRIu32" (diff %"PRIi32" us)\n", message.clock.tv_sec, message.clock.tv_nsec, (int32_t) (remote_time_ns - local_time_ns) / 1000);

	return SLASH_SUCCESS;
}

**Comment by schaefer01** [comment]
thank you!

On Nov 6, 2020, at 12:44 PM, Johan De Claville Christiansen <notifications@github.com<mailto:notifications@github.com>> wrote:



Here is our code to set and get the clock.

If you specify -1, it will set the local system time to the remote node. If you set it to zero, it will get the time without setting it, and if you specify a positive number the time will be set to that value.

static int slash_csp_cmp_time(struct slash *slash)
{
if ((slash->argc < 3) || (slash->argc > 4))
return SLASH_EUSAGE;

unsigned int node = atoi(slash->argv[1]);
int timestamp = atoi(slash->argv[2]);
unsigned int timeout = 1000;
if (slash->argc > 3)
        timeout = atoi(slash->argv[3]);

struct csp_cmp_message message;

csp_timestamp_t localtime;
clock_get_time(&localtime);

if (timestamp == -1) {
        message.clock.tv_sec = csp_hton32(localtime.tv_sec);
        message.clock.tv_nsec = csp_hton32(localtime.tv_nsec);
} else {
        message.clock.tv_sec = csp_hton32(timestamp);
        message.clock.tv_nsec = csp_hton32(0);
}

if (csp_cmp_clock(node, timeout, &message) != CSP_ERR_NONE) {
        printf("No response\n");
        return SLASH_EINVAL;
}

message.clock.tv_sec = csp_ntoh32(message.clock.tv_sec);
message.clock.tv_nsec = csp_ntoh32(message.clock.tv_nsec);

int64_t remote_time_ns = message.clock.tv_sec * 1E9 + message.clock.tv_nsec;
int64_t local_time_ns = localtime.tv_sec * 1E9 + localtime.tv_nsec;

printf("Remote time is %"PRIu32".%09"PRIu32" (diff %"PRIi32" us)\n", message.clock.tv_sec, message.clock.tv_nsec, (int32_t) (remote_time_ns - local_time_ns) / 1000);

return SLASH_SUCCESS;


}
