### ISSUE TITLE
kiss interface differences between C and Python

### ISSUE THREAD

**Issue by schaefer01** [libcsp/libcsp#178]
Hi,
 I'm coding a server/client where the server is python ubuntu and the client is an embedded c TI 432
   with a uart (mapped to a usb device).

 The c kiss interface has a place in its configuration for  every variable needed to initialize including 
   databits, stopbits, paritysetting and checkparity, but

 the python kiss interface does not have  databits, stopbits, paritysetting or checkparity, but does 
   have an API parameter named mtu, which is not passed into the lower level c interface call.

 Has this been tested by  you, and should I worry if not?

bob s.

**Comment by johandc** [comment]
I personally don't use the python bindings, use at your own risk. They were written as a contribution from gomspace.

A difference in interface is not necessarily a bug. Python probably has its own ways to initialise the serial port. Correct me if I'm wrong.
