### ISSUE TITLE
CSP_MEMFREE gives wrong answer on freertos AVR due to truncation

### ISSUE THREAD

**Issue by jlars07** [libcsp/libcsp#18]
csp_service_handler gives wrong answer on the CSP_MEMFREE port for freertos on AVR.

This is due to truncation of the argument given to malloc. Malloc takes type size_t, which is only two bytes on AVR. The value of 'size' is initialized to 1000000 and is thus truncated in the call to malloc.

Setting the initialized value of 'size' and 'max' to a value below UINT16_MAX results in the right answer.

**Comment by jledet** [comment]
Thanks for the bug report. I have changed the behavior to start with 10 KiB chunks for systems where size_t is less than 32 bits. Can you checkout 04fc7d5a0d64092a39b8135249dcb87ad4fe9859 and confirm that it fixes the problem?

**Comment by jlars07** [comment]
I can confirm that this fixes the issue.
