### ISSUE TITLE
example/python_bindings_example_server.py listens on different socket that it tries to read from

### ISSUE THREAD

**Issue by schaefer01** [libcsp/libcsp#181]
Again, I am using the uart, an ubuntu device using python connected to a ti 432 running C
The python code creates a socket, binds to the socket, listens on the socket and then follows by accept then read.
csp_listen in csp_port.c creates a queue to listen on, a packet is placed in the socket queue, but the accept call reads a different queue, the connection rx queue.  It seems an important step is missing transferring data from the socket's socket queue to the connection's rx queue.
 1. csp_accept in csp_io.c doesn't read the queue the csp_listen call in csp_port.c creates
 2. the accept call instead attempts to read the rx queue which is empty because there first needs to be a dequeue of the pointer to the packet from the socket queue and a re-enqueue of the pointer on the connection rx queue.
 3. the csp_read fails because the rx queue is empty because there was no tranfer of the packet from listen to accept.
 
help please.

**Comment by johandc** [comment]
There is nothing wrong with this.

The socket for the incoming connections is not the same as the socket for the incoming packets. That's normal.
