### ISSUE TITLE
csp_conn.c, csp_connect, assigns CSP_FCRC32 to local variable only, is not sent in packet flags

### ISSUE THREAD

**Issue by schaefer01** [libcsp/libcsp#183]
declared in csp_connect(), these variables are not assigned to the connection:
csp_id_t incoming_id, outgoing_id;

		outgoing_id.flags |= CSP_FCRC32;
		incoming_id.flags |= CSP_FCRC32;

I verified this by generating a packet, transmitting the packet, and looking at the flags.

Note also, csp_if_kiss.c, csp_kiss_rx, csp_crc32_verify() is called always, without checking the flags for CSP_FCRC32

I'm still trying to verify if the outgoing crc matches the recalculation of the crc and have found at least one bug,
  csp_kiss_rx() passes the packet minus the crc bytes in the packet count (4 bytes less) but the csp_crc32_verify() function subtracts the 4 bytes AGAIN, so it is generating a checksum on a shorter packet than it should.

**Comment by schaefer01** [comment]
I am also having issues with the function csp_ntoh32() in csp_endian(), which on ubuntu's gcc, does not reorder the bytes so much as generates a random number, but not for all uses in all places, which worries me.
I'm thinking of taking it out of inline and not having such a complex transform in a single code statement.

**Comment by johandc** [comment]
This is due to double crc. Both on Mac layer and on network layer.
