### ISSUE TITLE
csp_io.c, csp_read should disabiguate types of errors

### ISSUE THREAD

**Issue by schaefer01** [libcsp/libcsp#184]
At the lowest level of csp_read() is the call to pthread_queue_dequeue(), which has 3 types of errors that can be returned, 
get_deadline()  can detect a clock error, and can detect no time left, while for pthread_queue_dequeue itself, 
there may be no packet in the queue.

using zmq, of course, the packet will immediately be available, however for more distant devices, it would be useful to know that the read hasn't waited long enough versus there has been a deadline or clock error.

as it stands, csp_read() just sees csp__queue_dequeue return an error and doesn't know what particular error.

**Comment by johandc** [comment]
csp_read() is a blocking call. It either returns a packet within the time period or it does not. No further information should be needed. Unlike asynchronous APIs we do not return E_AGAIN or anything like that. Because csp_read supports blocking.
