### ISSUE TITLE
csp_buffer.c, csp_buffer_init() does not check for errors in "for" loop

### ISSUE THREAD

**Issue by schaefer01** [libcsp/libcsp#189]
first a buffer pool is created, the malloc is checked
then the queues are created, this too is checked,
then there is a for loop that enqueues the buffer pool addresses
but this for loop does not check for errors returned from csp_queue_enqueue

**Comment by johandc** [comment]
That is because the queue is completely empty. And the size has been set large enough to hold all the buffers. At the point of initialisation nobody has the reference to the queue, so it is safe to assume this.
