### ISSUE TITLE
License compatibility with MIT or Apache 2.0

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#192]
Hello,

libcsp seems to be under LGPL 2.1.  FreeRTOS, OTOH, is under MIT and doesn't support dynamic linking.  IANAL, but this seems incompatible to me.  Does libcsp offer exception for static linking?

Of course it's perfectly fine for libcsp project to use LGPL.  There is nothing wrong with it.  I just wanted to make sure that we are aware of it.

I'd be very nice if libcsp project add an exception saying that users can link against free software.

https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs
https://en.wikipedia.org/wiki/GPL_linking_exception

**Comment by johandc** [comment]
Sure we can add that. To be frank I don't care what you use it for. You seem to be into this, maybe you can come up with a suggestion to a better licence. We just want the most open license that still maintains the original licence text.

**Comment by yashi** [comment]
Thanks! I'll prepare a PR, then.

**Comment by yashi** [comment]
hmmm... I've added a PR with a license exception but I'm not sure that's really what we want.  My intention was to allow linking against any free and open-source software.  But the exception I came up with allows any proprietary program to use libcsp without providing object files to users, which LGPLv2 requires.  It certainly allows user to do anything with libcsp, though.
comments welcome, as always.

**Comment by benner** [comment]
> Sure we can add that. To be frank I don't care what you use it for. You seem to be into this, maybe you can come up with a suggestion to a better licence. We just want the most open license that still maintains the original licence text.

I have similar question. I need to link against not open project to. v2.0 has MIT license but v1.6 branch, which is till most popular version, has LGPL.   Can I assume 1.6 is MIT too?
