### ISSUE TITLE
Example csp_server_client error

### ISSUE THREAD

**Issue by 21212124** [libcsp/libcsp#195]
Hi,

I am trying to run the examples but I have the following error:
The line executed:
` $ sudo ./waf configure build install --with-os=posix --enable-examples -v`

![image](https://user-images.githubusercontent.com/30496643/110507912-c5982e00-8100-11eb-9a95-026c857bdc38.png)

Why does this happen?
Thank you

**Comment by JeremyDarcis** [comment]
Hello @21212124 !
I have the same error, can you tell me how you managed it please ? 
Thank you !

**Comment by 21212124** [comment]
Hi @JeremyDarcis,

I don't work on this project anymore but you can try these commands:

$ sudo apt install -y libzmq3-dev libsocketcan-dev
$ sudo ./waf configure --toolchain= --with-os=posix --prefix=install --enable-promisc --install-csp --enable-python3-bindings --enable-can-socketcan --with-rtable=static
$ sudo ./waf build install
$ sudo ./examples/buildall.py

Best regards.

**Comment by yashi** [comment]
You need to specify which UART driver to use.  Try:
```
./waf configure build --with-os=posix --enable-examples --with-driver-usart=linux -v 
```
