### ISSUE TITLE
Cannot access the official site 

### ISSUE THREAD

**Issue by ligun** [libcsp/libcsp#196]
I couldn't connect to the official site of libcsp (http://www.libcsp.org/).
It doesn't seem to exist.
Where can I get the information about the usage of the library?

**Comment by johandc** [comment]
It's working again now

**Comment by ligun** [comment]
Thank you for your support.
Now I checked the page, and it redirect to the GitHub repository.
Is it normal?

Do it have no usage or information pages currently?

**Comment by johandc** [comment]
Take a look in the doc sobfolder. That's what's available in the GitHub repository. Individual vendors selling products with CSP probably has their own documents too

**Comment by ligun** [comment]
Thank you.
I'll read it.
