### ISSUE TITLE
csp_route.c, csp_route_work has an issue with RDP

### ISSUE THREAD

**Issue by schaefer01** [libcsp/libcsp#198]
1. the #endif clause for RDP placed before end of the RDP clause:
#if (CSP_USE_RDP)
	/* Pass packet to RDP module */
	if (packet->id.flags & CSP_FRDP) {
		bool close_connection = csp_rdp_new_packet(conn, packet);
		if (close_connection) {
			csp_close(conn);
		}
		return CSP_ERR_NONE;
	}
#endif

	/* Pass packet to UDP module */
	csp_udp_new_packet(conn, packet);
	return CSP_ERR_NONE;

**Comment by johandc** [comment]
This is not a bug
