### ISSUE TITLE
if you open up the max port to actually be the max port, 63, csp_conn_init generates a floating point exception

### ISSUE THREAD

**Issue by schaefer01** [libcsp/libcsp#199]
in csp_conn_init()

    /* Initialize source port */
    srand(csp_get_ms());
    sport = (rand() % (CSP_ID_PORT_MAX - csp_conf.port_max_bind)) + (csp_conf.port_max_bind + 1);

   rand() % ( 63 -63)  results in floating point error

  on top of that, why do you even want to set a random initial source port?

**Comment by johandc** [comment]
The bind port cannot be the maximum port. So setting to 63 is an invalid input.
It is usually set somewhere between 16 and 32. The remainder of the ports should be available for source ports and outgoing connections.

The outgoing connections are ephemeral and it is just good practice to randomise this. So the risk of a connection conflict is reduced in the case the client reboots and the server still has the connection open.
