### ISSUE TITLE
interface between csp_if_kiss.c and usart_kiss.c does not check for tx driver errors

### ISSUE THREAD

**Issue by schaefer01** [libcsp/libcsp#201]
usart_kiss.c 
pointer to driver initialization:
 ifdata.tx_func = kiss_driver_tx;

the function: 
static int kiss_driver_tx(void *driver_data, const unsigned char * data, size_t data_length)

csp_if_kiss.c, the function cal, csp_kiss_tx:

    ifdata->tx_func(driver, start, sizeof(start));
   ifdata->tx_func(driver, esc_end, sizeof(esc_end));
  ifdata->tx_func(driver, esc_esc, sizeof(esc_esc));
  ifdata->tx_func(driver, data, 1);
  ifdata->tx_func(driver, stop, sizeof(stop));

the return status from  ifdata->tx_func(), i.e. kiss_driver_tx() is never checked.

**Comment by johandc** [comment]
We do not need to check outgoing interface success. Because on the case of a packet loss, retransmission takes place on a higher layer.

And what of the TX was unsuccessful? Wouldn't the correct behaviour be to continue transmit?
