### ISSUE TITLE
Make Windows CI machine green

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#212]
With #211, I made all Mac OS X machines pass and green but was unable to make Windows CI machines work.  Hope someone with Windows experience fix it.

**Comment by yashi** [comment]
@johandc, how about disabling the Windows CI machine on develop branch for now?  Because the CI is red all the time, we don't even bother to check it.  We can re-enable the machine once someone fixes it.

**Comment by johandc** [comment]
Yes. The CI system was setup by a now ex GS employee, so not sure if I can do that. Is it possible to do by changing the file on GitHub alone, then go ahead and remove it. I will merge right away.

**Comment by johandc** [comment]
This worked :)

I have access to Travis now, but we are out of credits. So i have talked to them about funding it as an OSS project, and hope to get reopened again.

**Comment by yashi** [comment]
Maybe it's time to move on to Github Action or some other CI services with free tier, buildkite, circleci, codeship...

**Comment by johandc** [comment]
Do you have experience with any of said systems?

**Comment by yashi** [comment]
Nop. But I have to move my free software repos to Github Action, anyway.  Do you have any preferences? Let's discuss it in #230.
