### ISSUE TITLE
Settle on a coding style

### ISSUE THREAD

**Issue by jledet** [libcsp/libcsp#22]
The CSP core team finally reached consensus on the placement of pointer asterisks :)

``` c
char *correct = "This is correct";
char * bad = "This is not";
```

Fix it in the entire codebase...

**Comment by johandc** [comment]
Oh, and another thing:

```
Wrong   - "Fix the pointer asterisks!"
Correct - "Fix the pointer asterisks"
```

CSP developers should try to remain calm at all times, even when they agree on new coding standards. :)

**Comment by johandc** [comment]
How far did we get with this thing?

**Comment by jledet** [comment]
I think it will be a work in progress for quite some time. I try to fix the pointers when I come across an incorrect one, but I don't think we should go through all the files manually. We could probably write a small script to do it, but I don't think it's a high priority task :)

**Comment by jledet** [comment]
I suggest we just use the GomSpace coding style which is basically equivalent to the Linux one: https://www.kernel.org/doc/Documentation/CodingStyle

**Comment by jledet** [comment]
I'm closing this for now. If anyone have good arguments for a different coding style, please reopen.
