### ISSUE TITLE
csp_send return value

### ISSUE THREAD

**Issue by jledet** [libcsp/libcsp#23]
Unfortunately, the original version of CSP used 1 to indicate successful transmission in interface tx functions, and 0 to indicate failure. In the name of backward compatibility, this return value has been kept.

The remaining CSP calls return one of the defines from csp_error.h, which use 0 for success, and negative integer error codes. This gives an irregular API, and could lead to confusion since e.g. csp_send(...) == CSP_ERR_NONE is _true_ when the transfer _failed_.

We can easily change the interface tx functions to return error codes. I suggest we also change the API for v1.1 so csp_send and interface tx functions return CSP_ERR_NONE on success like the rest of the API.

**Comment by jledet** [comment]
I have fixed the interface return values.

I'm not sure what to do with csp_send and especially csp_transaction (which just _begs_ for an API that returns the number received bytes).

**Comment by johandc** [comment]
Let's not change csp_send right now. We could begin the work in a new branch and slowly port all our software to the changed API while testing it.

**Comment by johandc** [comment]
This is fixed in CSP 2.0
