### ISSUE TITLE
Move Travis CI to other CI

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#230]
Travis CI [does not offer free tier](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) any more.  And said open source offer is [already blocked](https://twitter.com/james_hilliard/status/1336081776691843072).

So, we must find some CI services with
- No cost
- Linux, Windows, Mac must be supported

This is related to #212.

**Comment by johandc** [comment]
I got a mail from Travis they will be giving us some OSS credits.

**Comment by yashi** [comment]
That's great.  Hope it will last until we migrate to another one.  I'll keep posting if I get something new.
