### ISSUE TITLE
service_handler: partial csp_sendto_reply() when failed to csp_buffer_get()

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#232]
https://github.com/libcsp/libcsp/blob/941a34be547b9e35d728dc9519bc554ef5cc1346/src/csp_service_handler.c#L261-L264

At this point, we might have `packet != NULL`.  Thus after `break` it will try to `csp_sendto_reply()` it.  Is this intended?

**Comment by johandc** [comment]
After the break, it will go to the end of the while loop, and therefore NOT call csp_sendto_reply().
