### ISSUE TITLE
Build libcsp with FreeRTOS on CI

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#233]
I think it's a good idea to at least build libcsp against FreeRTOS on CI.

@johandc, I'm not familiar with FreeRTOS but I'd like to, first, test it locally and deply it to CI.  If you have a simple build steps, would you mind to share it with me?  It doesn't have to be a comprehensive at all.

**Comment by johandc** [comment]
I think there is some kind of posix port of freertos available, that could be used to run basic tests.

**Comment by yashi** [comment]
csp_arch.c on FreeRTOS for POSIX is done.  I'd like to host it under libcsp if you are OK with it.

I wanted to cross build for ARM  so that we could test FreeRTOS for ARM on QEMU.   The blinky worked on QEMU but I couldn't integrate picolibc with it.   We can migrate to Non-POSIX later I assume.

https://github.com/spacecubics/libcsp-freertos

**Comment by johandc** [comment]
Very nice indeed. Do you think it can run automatically with GitHub actions too?

I will setup the repo and provide you with write access

**Comment by yashi** [comment]
Yes, I think I can.

**Comment by johandc** [comment]
Done
https://github.com/libcsp/libcsp-freertos
