### ISSUE TITLE
Fix CI with meson

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#238]
On the current Travis CI, we support
- Ubuntu 16.04
- Ubuntu 18.04
- Ubuntu 20.04

These platforms have different version of the Meson build system:

Ubuntu | Meson | End of Standard Support | End of Life 
--- | --- | --- | ---
16.04 (LTS) | [0.29](https://launchpad.net/ubuntu/xenial/amd64/meson/0.29.0-1) | April 2021 | April 2026
16.04 Update (LTS) | [0.40.1  ](https://launchpad.net/ubuntu/xenial/amd64/meson/0.40.1-1~ubuntu16.04.1) | April 2021 | April 2026
18.04 (LTS) | [0.45.1](https://packages.ubuntu.com/bionic/meson) | April 2023 | April 2028
18.04 Update (LTS) | [0.45.1](https://packages.ubuntu.com/bionic-updates/meson)| April 2023 | April 2028
20.04 (LTS) | [0.53.2](https://packages.ubuntu.com/focal/meson) | April 2025 | April 2030

Unfortunately, some feature we use doesn't not exist in old version of meson, namely
- From 0.36, the command was renamed from `meson.py` to become `meson`
- From 0.42, `setup` sub-command is added
- From 0.54, `compile` command gained `-C` option

That said, even with 16.04 with updates, we can't really support Meson 0.29.
- Meson is too old
- It's already End of Standard Support

If we are OK to support 18.04 and 20.04, we can set the minimum version to 0.45.1.

**Comment by johandc** [comment]
Let's just remove the two older ones and support from 20.04 and up. It also uses less CI ressources.

We should consider ARM and AVR as build targets.
