### ISSUE TITLE
Add RTT to routing table

### ISSUE THREAD

**Issue by johandc** [libcsp/libcsp#24]

**Comment by jledet** [comment]
Is the reason for this to have automagical calculation of packet/connection timeouts for RDP?

**Comment by johandc** [comment]
Not exactly on RDP, because that is controlled on the client anyways. The point where it could be helpful are where the ground-station must execute something in sequence, without knowing wether or not the satellite is connected through radio link or serial port.

In this case you could do something like csp_send(conn, packet, csp_get_rtt(conn->id.out) + 100);

This would mean that the function will always leave 100 ms for processing in addition to the link RTT. The RTT value could have a default value that was conservative, and then updated when a subsystem is pinged.

Also during operations this feature would be nice whenever the baud-rate changes on the radio link.

In the end, yes. I think it could also be used to set some good automatic values for an RDP connection. Only problem here is that they cannot be changed without closing and re-opening the connection.
