### ISSUE TITLE
atomics

### ISSUE THREAD

**Issue by johandc** [libcsp/libcsp#243]
Consider using atomics for simple locks (such as the source port lock)

- [x] sport lock
- [x] connection table lock

**Comment by johandc** [comment]
If we can add an interface that uses atomics when availabe, and reverts to using binary semaphore's when not. It would be nice.

**Comment by yashi** [comment]
Does it mean we'll be using C11 instead of C99?

**Comment by johandc** [comment]
I completely removed the source port lock by pre-assigning source ports to each connection. I think it's pretty clever, because it actually took a O(n * m) search down to O(1).

For this to work, we assume that number of connections is lower than the number of port numbers available for outgoing (typically 48). There is a compile time check for this.

**Comment by johandc** [comment]
I added C11 atomics for the connection table lock using the:

  `atomic_compare_exchange`

Function. The compiler typically knows what to do. But in the case of Cortex-M0 it's not supported, and it makes an external function call to a user implementation. I therefore added an example in 'contrib/atomics/atomics_freertos_gcc.c' to show how the user may implement such thing on Cortex-M0 and FreeRTOS. It's typically just deactivating interrrupts while performing the compare and exchange.

On more advanced ARM systems such as cortex M3, M4, M7, A9... and up, as well as X86, and ARM64, the compiler has assembler intrinsics that performs this using dedicated instructions.

The removal of the sport and conn locks has reduced a M0 image size by 300 bytes .text and 100 bytes .bss.
