### ISSUE TITLE
Location of csp_autoconfig.h

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#251]
We no longer install `csp_autoconfig.h` so it doesn't really matter in practice but where should we put generated `csp_autoconfig.h`? Currently we have two locations:

- `include/csp_autoconfig.h`: waf
- `csp_autoconfig.h`: meson, cmake (due to following meson)

To find `csp_autoconfig.h`, we currently specify the top directory (build top to be precise) as a include directory.  But if we move it under `include/`, we have one less include directory to worry about.

Another thing we need to consider is that `csp_autoconfig.h` is implicitly mandatory for applications linking against `libcsp.a`.  That is, for meson based project for example, `csp_dep` must have a include directory containing `csp_autoconfig.h`.

We could align with other header files; under `include/csp/` and do `#include "csp/csp_autoconfig.h"`.  Just like any other header file we have.

Thoughts?

**Comment by johandc** [comment]
I agree, let's move it to "csp/csp_autoconfig.h".

**Comment by yashi** [comment]
It seemed a simple job turned out be a can of warm.... Meson doesn't even allow me to place the file in sub directory.
I'll tackle this after zephyr merge. Please keep this issue open and assign to me.  

Meanwhile, I just fixed `waf` to put `csp_autoconfig.h` in the build directory to align it with meson and cmake.

**Comment by Buzzzz** [comment]
I am packaging libcsp for cross-compilation as a local debian package and have found that changing all include directives for this header to `#include <csp/csp_autoconfig.h>` (insert csp/) solves all the ugliness of needing the csp directory as another include path element.
This used the waf build. If the other builds work fine, can it be committed?

**Comment by yashi** [comment]
@Buzzzz, would you please test the PR?

**Comment by yashi** [comment]
note that
- Waf: Should work.
- Meson: Explicitly disabing libcsp.a installation.  Easy to fix but I'd love to wait for a comment from @johandc.  The current situation is broken; it installs header files but not libcsp.a.
- CMake:  ~No installation is supported.~ Implemented by #446

**Comment by Buzzzz** [comment]
Yashi-San, I have successfully completed a waf build and install from the PR. Looks very good. Thanks!

**Comment by yashi** [comment]
Since @johandc have once agreeded renaming it in the past, I'm merging this.

**Comment by yashi** [comment]
If someone need a proper install target in either Meson or CMake, please open a new issue.  Thanks.
