### ISSUE TITLE
Storage interface for settings

### ISSUE THREAD

**Issue by johandc** [libcsp/libcsp#26]
The routing table in CSP should be available as a struct array, that could be used by the user to easily store and restore the configuration to/from EEPROM or in flash. This is to allow generic CSP products to be shipped out, configured by the user and then stored in the flash configuraiton.

I suggest that CSP will support a callback function pattern for store and restore. CSP will take care of formatting and parsing the data, and the user provides a function that will store the char \* data and int length, from CSP.

This may even be extended in the future such that node address, buffer sizes and other options could be stored along with the routing table, and make CSP even more flexible for the users.

The aim is to provide a generic CSP software for products like the EPS that we will "mass-produce" without re-compiling the software for each user-defined routing table.

**Comment by jledet** [comment]
Implemented in cidr branch, requires review before merge.

**Comment by johandc** [comment]
This has been solved with csp_rtable_parse() that can load a routing table from string.
