### ISSUE TITLE
Document about CMake

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#260]
We've added CMake support but not yet documented.

@johandc, where should I document about the build systems? `README.rst` or under `doc/`?

**Comment by yashi** [comment]
#231

**Comment by johandc** [comment]
first of all. I want to move to .md. 
You should put it into doc with links from readme. So it works on GitHub.
The major items from the  changelog should be promoted to the front page too.

**Comment by yashi** [comment]
Just tried to see how well rst to gfm conversion works with [pandoc](https://pandoc.org/).  `literalinclude` doesn't work with gfm and GitHub is not willing to support it.

**Comment by johandc** [comment]
Okay I think we should just copy the text referred to, rather than using fancy features like that one.
