### ISSUE TITLE
Convert rst documents to gfm

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#262]
#260

We'll convert all documents from reStructuredText to GitHub Flavored Markdown.

In order to do so, I will use [`pandoc`](https://pandoc.org/).  Unfortunately gfm doesn't support all features we use in our documentation.  Namely:

- literalinclude
- toctree
- ref

We also have some syntax variations that pandoc failed to convert. So, my proposing steps for conversion is:

- [x] tweak *.rst
  - [x] leading white space at list
  - [x] leading whitespace at code bock
- [x] replace unsupported features
- [x] grand conversion with pandoc
- [x] tweak *.md
  - [x] reference fixup
  - [x] monospece with backtick

Remaining big one is structure.rst.

**Comment by johandc** [comment]
Looks good
