### ISSUE TITLE
set csp_prio field per packet, not per connection.

### ISSUE THREAD

**Issue by johandc** [libcsp/libcsp#27]
Today only one csp_prio may be selected for each connection using the csp_connect call. It should be possible to set different priorities on packets in the same connection. So the prio field should be added to csp_send, or we may extend the api with csp_send_prio(prio, conn, packet) which will then override the default priority set in the connection.

**Comment by jledet** [comment]
On 2012-01-12 10:55, Johan De Claville Christiansen wrote:

> Today only one csp_prio may be selected for each connection using the csp_connect call. It should be possible to set different priorities on packets in the same connection. So the prio field should be added to csp_send, or we may extend the api with csp_send_prio(prio, conn, packet) which will then override the default priority set in the connection.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/GomSpace/libcsp/issues/27
> Yes, or at least we should make some kind of helper function to
> temporarly switch the connection priority. I think we should think about
> making a csp_setsockopt function and move the RDP options to this as well.

I agree with csp_send_prio but think the prio argument should be
appended (conn, packet, prio) instead of being first.
