### ISSUE TITLE
Do not print log messages in ISR context

### ISSUE THREAD

**Issue by jledet** [libcsp/libcsp#31]
The functions ending in _isr are meant to run in interrupt context only. However, some of them contains log messages. Since interrupt stacks are often very limited, it is generally a no-go to do printf's in ISR context.

I just hit a couple of reboots on AVR due to csp_buffer_get_isr() doing a csp_log_error("Out of buffers\r\n") when it runs out of buffers.

I'm not sure what the correct solution to this is. Maybe we could come up with something like trace_printk?

**Comment by johandc** [comment]
Just remove the line for now. It tends to do more trouble than good (loops of "out of buffers" happens occasionally).
In the future we could implement a callback / user action on CRITICAL events. If you are out of buffers you should find out why that happens and solve the problem. A reboot would in fact not be a bad thing to do in this case.

**Comment by johandc** [comment]
Pretty sure this is fixed by now. Haven't found any for some years :)
