### ISSUE TITLE
Enable auto delete merged branches

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#317]
It'd be nice if we remove merged branches in the repo.  There is an option for this.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

Or, is there any reason we want to keep them?

**Comment by johandc** [comment]
Done

**Comment by yashi** [comment]
Thanks.  Is it ok to remove remaining merged branches by hand?

**Comment by johandc** [comment]
Yes
