### ISSUE TITLE
csp/csp_autoconfig.h: No such file or directory

### ISSUE THREAD

**Issue by sandesh9** [libcsp/libcsp#32]
Hi, I am trying to compile source code of hmac  from crypto. But I received this error and checked the CSP folder for csp_autoconfig.h. I did not  found this header file. Can anyone help me regarding this issue.

**Comment by johandc** [comment]
csp_autoconfig.h is an automatically generated configuration file. It's made by the 'waf' buildsystem, based on your configuration parameters. Normal build procedure is "./waf configure build". (Read more about building here: https://github.com/GomSpace/libcsp/wiki/Compiling-CSP)

If you would like to compile HMAC as standalone, without being integrated with the library, you should remove the references to csp_autoconfig.h and the #ifdef's in the code files.

Here is the typical contents of a config:

#define GIT_REV "46d67426"
/\* #undef CSP_FREERTOS _/
/_ #undef CSP_POSIX _/
#define CSP_WINDOWS 1
/_ #undef CSP_MACOSX _/
#define CSP_DEBUG 1
/_ #undef CSP_USE_RDP _/
/_ #undef CSP_USE_CRC32 _/
/_ #undef CSP_USE_HMAC _/
/_ #undef CSP_USE_XTEA _/
/_ #undef CSP_USE_PROMISC _/
/_ #undef CSP_USE_QOS _/
/_ #undef CSP_BUFFER_STATIC _/
#define CSP_BUFFER_COUNT 12
#define CSP_BUFFER_SIZE 320
#define CSP_CONN_MAX 10
#define CSP_CONN_QUEUE_LENGTH 100
#define CSP_FIFO_INPUT 10
#define CSP_MAX_BIND_PORT 31
#define CSP_RDP_MAX_WINDOW 20
#define CSP_PADDING_BYTES 8
#define CSP_LITTLE_ENDIAN 1
/_ #undef CSP_BIG_ENDIAN */

I believe that the define that the hmac files are looking at is:
CSP_USE_HMAC

Regards,
Johan.

**Comment by sandesh9** [comment]
Hi Johan,
Thank you the first option works.
regards,
Sandesh
