### ISSUE TITLE
python3 binding is broken

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#322]
With the commit 407e89661d7, `csp_socket_t` is no longer `csp_conn_t`.  This caused various parts of the bind to be broken.

**Comment by johandc** [comment]
Oh yes

**Comment by stephan-ack** [comment]
I'm guessing this is also related to this error below that I am seeing? Afaik, "address" has been moved away from he csp_conf_s struct in CSP2.0?

```
../src/bindings/python/pycsp.c:105:47: error: ‘csp_conf_t’ {aka ‘struct csp_conf_s’} has no member named ‘address’
  105 |  if (!PyArg_ParseTuple(args, "bsss", &csp_conf.address, &csp_conf.hostname, &csp_conf.model, &csp_conf.revision)) {
```

**Comment by johandc** [comment]
Yes, in CSP 2.0 each interface has it's own address. So there is no longer a global CSP node id.

**Comment by gsantamarina** [comment]
Will this be fixed soon? Getting the same error when trying to compile the python3 bindings.
