### ISSUE TITLE
CFP2_SENDER_MASK 

### ISSUE THREAD

**Issue by jsrmalvarez** [libcsp/libcsp#343]
Hi, I'm playing with CSP over CAN.

I can't find any CFP 2.0 specification (except the code itself) so maybe this is not an issue.

In the definition of CFP2_SENDER_MASK (csp_if_can.h file, line 109)
shouldn't it be 0x3F instead of 0x1F, since CFP2_SENDER_SIZE is 6 bit?
Otherwise we are losing the MSb of the Sender ID field.

**Comment by johandc** [comment]
The specification is in doc/ here:
https://github.com/libcsp/libcsp/blob/develop/doc/CSP%202.0%20Specification%20-%20Ark1.pdf

**Comment by johandc** [comment]
The CFP2_SENDER_SIZE is correct 6 bits.
(note the destination field have been swapped further up in the header, in the actual implementation).
The CAN ID is not long enough that the entire sender id can be contained within. So the upper byte of that is transmitted as part of the first CFP_BEGIN packet.

**Comment by jsrmalvarez** [comment]
Thanks johandc for your reply.

Yes, the size of 6 bit is correct.

But the mask CFP2_SENDER_MASK is set to 0x1F.
The mask is taking only 5 bit. Shouldn't it be 0x3F to take the 6 bit?

**Comment by johandc** [comment]
I was to quick to conclude and read MSB not MSb. Yes this is a bug.

**Comment by jsrmalvarez** [comment]
My last phrase of the issue description was unnecesary and misleading.

**Comment by johandc** [comment]
Fixed in develop
