### ISSUE TITLE
CCSDS over CSP

### ISSUE THREAD

**Issue by PaulMadle** [libcsp/libcsp#346]
Hi all, 

Apologise if this is not really the right forum to ask questions but I am trying to see if there is a way to integrate CCSDS protocol over the top of CSP. 
I am thinking that the CSP UDP service might offer a starting point. I am thinking that I could put the CCSDS data link layer TM/TC frames into a CSP UDP frame. The CCSDS would then take care of retransmissions of telecommands and file transfer in place of the RDP protocol defined in CSP. Does this sound feasible? 2 questions:
- What is the maximum data payload in bytes for a single CSP UDP frame?
- Does the CSP UDP frame include some kind of error detection (e.g. CRC).

I tried looking through the documentation and couldn't find answers to these questions. The interface I am concerned with here is the Space<>Ground interface rather than e.g. CAN.

Many thanks,

Paul.

**Comment by johandc** [comment]
CSP 2.0 supports frame sizes of 2026 bytes on CAN bus, and higher on other links. Up to 16 bit length. So 65 KB.

CSP includes CRC32C.

**Comment by johandc** [comment]
I don't see the reason why you would use CSP over a single link to encapsulate something else, unless the link you are using is CSP already.

CSP is used for routing on board and on ground. So if you don't use routing. Then CSP is just overhead.

**Comment by PaulMadle** [comment]
Thanks @johandc... Much appreciated. The reason to consider this encapsulation is simply necessity due to the selection of otherwise incompatible systems. Agreed that it is an overhead. Thanks for the numbers :)

**Comment by PaulMadle** [comment]
Many thanks for your wisdom @johandc, I am also trying to understand CSP 1.0 protocol rather than CSP 2.0. Is there a spec for this CSP 1.0 protocol?

**Comment by johandc** [comment]
CSP 1 is a 4 byte header. It can be seen on the Wikipedia page of cubesat protocol. CSP 2 is 6 byte header and the spec can be found in the doc folder.

**Comment by PaulMadle** [comment]
Fantastic, thankyou... I can see the header format for CSP 1.0 on https://en.wikipedia.org/wiki/Cubesat_Space_Protocol.
Is there something that specifies how this CSP message gets segmented into CAN frames for CSP 1.0?

I am aware that the first CAN frame in a sequence of CAN frames maps some of the fields in the CSP 1.0 header into the CAN 29 bit ID field and then some other fields into CAN data payload... Is there information on this for CSP 1.0?

**Comment by johandc** [comment]
Yes that information is in csp_cfp.c / .h here on GitHub.

**Comment by PaulMadle** [comment]
Brilliant, thankyou @johandc
