### ISSUE TITLE
Implement conn table as open list and closed list

### ISSUE THREAD

**Issue by johandc** [libcsp/libcsp#36]
The current table lookup for connections, scans the entire connection list, even closes connections are checked before looping to the next element. In CSP the number of active open connections should be rather small, therefore it would make sense to make a linked list of open connections, rather than using the table itself. This will cost a bit more memory if pre-allocated connection objects are chosen, but it would be quicker. It also allows for a more relaxed use of malloc where a number of statically pre-allocated elements can be inserted into a connection-closed list during initialisation from which new connection objects can be found. When this list is empty, there could be a flag which indicates wether or not to allow extension of the list using malloc. A flag could be added to the connection object which tells the conn_close() handler wether or not the object is allowed to be free'd or if it should be put back on the connection-closed list.

**Comment by johandc** [comment]
The same implementation (with static preallocation and relaxed malloc) could be done for the buffer pool.
Comments are welcome :)

**Comment by jledet** [comment]
I agree. We could just use the same approach as the buffer pool with a free list. I like the idea of allowing dynamic allocation of elements (most likely up to a predefined maximum so a bug cannot eat up all the memory). This way we can keep a small, fast pool for the general use case and still be able to handle a busy period. The dynamic allocation should of course be configurable at compile time.

**Comment by johandc** [comment]
Dynamic allocation has been dropped as a concept.

Also the scan of the conn table might actually be faster than invoking a queue call. All incoming traffic uses the port array which is O(1) lookup. And all outgoing traffic uses the next connection in the list, which is typically empty, so also a O(1) with the potential for O(n) in the case all connection but one is free.

I removed the sport O(n * m) effectively, so let's keep the conn table simple and avoid OS interaction as much as possible.
