### ISSUE TITLE
Porting Guidelines to different OS and baremetal Software

### ISSUE THREAD

**Issue by satzguyz** [libcsp/libcsp#375]
Hello Experts,
Is there any porting guidelines (APIs used for porting) to define the list of ports need to be made for various OS, Platform and interfaces?
Example: Folders like interfaces, arch, drivers has the porting APIs. Anything in addition I need to consider ?

**Comment by johandc** [comment]
That's pretty easy. You go into https://github.com/libcsp/libcsp/tree/develop/src/arch and implement those files for your architecture.

Bear in mind that CSP relies on queues. If your OS is bare-metal you will have to write your own queue implementation. Another thing it uses is the blocking queue reads, which you will have to implement in a polling interface instead. So baremetal is not completely simple.
