### ISSUE TITLE
Potential Use case of Promiscuous Mode

### ISSUE THREAD

**Issue by satzguyz** [libcsp/libcsp#378]
Hello Experts,

What are all possible use case of the CSP Promiscuous mode ? Does it consume more memory/buffer if it got enabled ?

**Comment by johandc** [comment]
Promiscious mode is good for routers to pick up traffic on one segment that is destined for another segment. It can also be used for logging of data. The memory backlog depends on the burstyness of the data, and the processing power of the receiver. This is also known as the time bandwidth product.
