### ISSUE TITLE
csp_buffer_get does not set the length field of the packet buffer it returns.

### ISSUE THREAD

**Issue by Taylorr82** [libcsp/libcsp#385]
It's strange to have to set the length of the packet manually when the function to return a packet has a size parameter

**Comment by johandc** [comment]
The size parameter is not meant to be inserted, it is meant as a maximum size of the allocation. The size field should rather be removed, now that CSP buffers are fixed size.

**Comment by Taylorr82** [comment]
Interesting, they've been a fixed size, statically allocated since at least version 1.6 (the one we're using on our project). I can make a commit here that will remove the size field if you'd like. 

Perhaps there should be an abstraction function to set the length field of the packet, does that exist already in this version?

**Comment by johandc** [comment]
Fixed
