### ISSUE TITLE
When building a C++ program, need to add extern "C" block around libcsp includes.

### ISSUE THREAD

**Issue by negatratoron** [libcsp/libcsp#409]
Compiler: g++ 11.3.0

Expected behavior: C++ programs compile and link against libcsp just by including the appropriate header files and linking the object files.

Actual behavior: Get the linker error ``undefined reference to `csp_init()'``

We can work around this just fine for now by adding `extern "C"` blocks around the libcsp includes.  However, if libcsp pulled in any libraries that had their own C++-related macros, this workaround might not work.

---

Reproducible example: In a new project directory:

Clone libcsp into `lib/csp` (as done here: https://github.com/spaceinventor/csh)

meson.build file:
```
project('TestProgram',
	'cpp',
	subproject_dir: 'lib'
)

csp_dep = dependency('csp', fallback: ['csp', 'csp_dep'], required: true)

main = executable(
	'main',
	[ 'src/main.cpp' ],
	dependencies: [csp_dep]
)
```

src/main.cpp file.  Program compiles and links after `extern "C"` lines uncommented:
```
// extern "C" {
#include <csp/csp.h>
// }

int main() {
  csp_init();

  return 0;
}
```

**Comment by yashi** [comment]
@negatratoron Please try the PR against real C++ programs.  And let me know how it works.

**Comment by negatratoron** [comment]
Thanks, the issue does not reproduce with commit [7e6d365](https://github.com/yashi/libcsp/commit/7e6d3657144c101cc4958257edf4c35866288562) @yashi
