### ISSUE TITLE
server_client example does not accept -d (debug) option, contrary to usage message

### ISSUE THREAD

**Issue by Buzzzz** [libcsp/libcsp#414]
The code in main() in examples/csp_server_client.c parsing the options with getopt() does not accept the -d option, even though the usage message says it does. The switch() does not handle `case 'd':`.

**Comment by yashi** [comment]
Thank you @Buzzzz.  It should be fixed.

**Comment by Buzzzz** [comment]
The `d:` is still in the getopt string. Maybe delete that as well? Thanks!

**Comment by yashi** [comment]
Ah, thanks.  Please review.
