### ISSUE TITLE
Some files don't end in newline, which is not proper C

### ISSUE THREAD

**Issue by Buzzzz** [libcsp/libcsp#419]
The files
```
src/csp_port.h
src/csp_rdp.h
src/csp_rdp_queue.c
src/csp_rdp_queue.h
```
do not end in a newline. This causes undefined behavior according to C11, J.2, Undefined behavior
> A nonempty source file does not end in a new-line character which is not immediately
preceded by a backslash character or ends in a partial preprocessing token or
comment (5.1.1.2).

Interestingly, .clang-format contains `InsertNewlineAtEOF: true` so it seems running the formatter will fix it.

**Comment by yashi** [comment]
Thanks @Buzzzz.  I've added a PR to fix it.  Please review.

`InsertNewlineAtEOF` was [just added ](https://github.com/libcsp/libcsp/commit/e13e947685ee581f5daec72668b7db98e14b9619)the other day.
