### ISSUE TITLE
Tag v2.0

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#433]
It's been long over due to release version 2.0.

**Comment by tniessen** [comment]
Hi @yashi! We are using libcsp 1. When libcsp 2.0 is tagged, will it be considered to be at least as stable as libcsp 1, or should we wait before upgrading?

**Comment by yashi** [comment]
Software in general do have many bus in .0 releases that's because users tend to wait until it's released. Libcsp is no exception I'd say.

Please help us squash as many bus as possible by using it!

Thanks

**Comment by michalkaptur** [comment]
Hi @yashi, do you plan on releasing v2 anytime soon? What would be the right version to use until then, [develop](https://github.com/libcsp/libcsp/tree/develop) or [libcsp-2-0](https://github.com/libcsp/libcsp/tree/libcsp-2-0)?

I couldn't find the branching policy neither in the readme nor in the docs.

**Comment by yashi** [comment]
Taken from https://github.com/libcsp/libcsp/issues/395#issuecomment-1403199937

> - `develop` : The development branch. All new things should go here. And this is the default branch. This will be 2.1 or something else.
> - `libcsp-1` : libcsp version 1.x
> - `libcsp-2-0` : libcsp version 2.0
> - `master` : This one might be confusing. But it points to libcsp-1 and we leave it there for backward compatibility.

And, Yes, we should document this in the README.  Thanks.

**Comment by yashi** [comment]
`v2.0` is just tagged.
