### ISSUE TITLE
Have a nice logo

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#441]
It would be nice if we had an attractive and iconic logo. Does anyone have some artistic skills to share?

**Comment by johandc** [comment]
We could put something on fiver and ask for some ideas.

**Comment by yashi** [comment]
I've decided to generate with AI but I guess I'm not a prompt engineer :grin: 
![Gemini_Generated_Image](https://github.com/libcsp/libcsp/assets/10152/bda46330-8c58-4b59-8667-8408b8473b1e)
![image](https://github.com/libcsp/libcsp/assets/10152/ab7fce6f-b041-4295-bc90-49cd43dba65a)
![Gemini_Generated_Image (1)](https://github.com/libcsp/libcsp/assets/10152/987d1bc0-49ce-4e75-8020-3278d8a24012)

**Comment by pr0me** [comment]
Hey, hope you don't mind me chiming in :)
I think the middle one is super sleek, a little weak in recognition value maybe, though.

I also had a go at it, let me know what you think (or if I should stop spamming this issue)

![pr0me_Design_a_minimalist_and_representative_logo_for_the_Cubes_3a8d3111-2ebd-4e76-bf67-aaf942dc06f9](https://github.com/libcsp/libcsp/assets/5177161/3593b51e-19f4-4683-a627-b59905df8872)
![pr0me_Design_a_minimalist_and_representative_logo_for_the_Cubes_5af489d9-bb57-490a-ac0a-9b09fb1d7656](https://github.com/libcsp/libcsp/assets/5177161/c4b062d7-3e9f-4dd2-ba1e-a766ae96d88a)
![pr0me_A_minimalist_and_representative_logo_for_the_Cubesat_Spac_926ce216-0344-4454-87af-a86d4e0b7ef5](https://github.com/libcsp/libcsp/assets/5177161/963f1a5e-1996-42e3-a526-f582a26b3a35)

**Comment by yashi** [comment]
Nice. Love that.

**Comment by pr0me** [comment]
any of the three in particular?
then I could generate variations, if you'd like

**Comment by yashi** [comment]
That's something not my job.  I'm assinging @johandc for this. :grin:

**Comment by johandc** [comment]
I think we may adopt both styles.

I like this concept for an official "small logo": 
![image](https://github.com/libcsp/libcsp/assets/545264/077ec05b-18b1-4912-a828-e92502c953f1)

I like this artwork for a welcome page:
![image](https://github.com/libcsp/libcsp/assets/545264/d925c6d3-7100-4acc-bbca-fab9894f9088)

**Comment by yashi** [comment]
![image](https://github.com/libcsp/libcsp/assets/10152/17079f2c-2fae-4ffa-a0bc-500fcdc1bff2)

**Comment by yashi** [comment]
spamming a few more.

![DALL·E 2024-03-12 21 47 18 - Design a modern and minimalistic logo featuring the letters 'CSP' alongside the silhouette of a CubeSat satellite  The CubeSat should be stylized and  webp](https://github.com/libcsp/libcsp/assets/10152/9bb857a5-85b5-47d5-8623-574ebe5eb0f2)
![DALL·E 2024-03-12 21 47 17 - Design a minimalist icon for libcsp that subtly incorporates the CubeSat theme without overly emphasizing cubic shapes  Aim for a balance between simp webp](https://github.com/libcsp/libcsp/assets/10152/bf7b017b-cf93-4e6b-b594-9cf19cf870a0)
![DALL·E 2024-03-12 21 47 13 - Create a flat design icon for libcsp, emphasizing simplicity and modernity suitable for a CubeSat communication protocol  The icon should focus on fla webp](https://github.com/libcsp/libcsp/assets/10152/eb8f59d6-c913-4c85-8845-3f18f1b6eea0)
![DALL·E 2024-03-12 21 47 11 - Design a sleek, modern, and simple icon for libcsp, a library protocol used in CubeSats  The icon should encapsulate the essence of satellite communic webp](https://github.com/libcsp/libcsp/assets/10152/35f288cb-6bd7-4d02-8f8d-bb2aff57b45a)
![DALL·E 2024-03-12 21 47 10 - Design a sleek, modern, and simple icon for libcsp, a library protocol used in CubeSats  The icon should encapsulate the essence of satellite communic webp](https://github.com/libcsp/libcsp/assets/10152/d79f94d3-e494-4abc-827a-4e4e313595bc)

**Comment by pr0me** [comment]
the first one is awesome!
I think it's clean enough to make an official logo, while still having nice graphics.
Should also be fairly recognizable in favicon size etc.

**Comment by yashi** [comment]
let's revisit this in a while. I'm closing this for now.
