### ISSUE TITLE
Unclear/outdated docs how to use CAN interface

### ISSUE THREAD

**Issue by Buzzzz** [libcsp/libcsp#442]
I'm trying to send a single message via CAN. The Linux system has a single "can0" device. I can send messages fine using a CAN RAW socket. The physically connected remote system has a candump process reading and acknowledging all messages. Think point-to-point topology. So far, so good.

Now I try to use libcsp for CAN message sending. There's no routing, all messages shall go through can0.

The Wiki at https://github.com/libcsp/libcsp/wiki/Client-and-server-example says to initialize a
`struct csp_can_config can_conf = {.ifc = "can0"};` but there's no such struct. I don't know what to fill in below at the line marked SOME MAGIC HERE. Can anyone provide a clue? Thanks!

```
...some includes elided...
#include "csp/csp_types.h"
#include "csp/csp.h

int main(void) {
    csp_init();

    /* SOME MAGIC HERE TO USE can0 for all traffic. */

    /* 1. No csp_connect(), since we use the connection-less mode. */
    /* 2. Get packet buffer for message. */
    csp_packet_t *packet = csp_buffer_get(256);
    if (packet == NULL) {
        csp_print("Failed to get CSP buffer\n");
        exit(1);
    }
    /* 3. Fill payload. */
    int     i = sprintf((char *) packet->data, "%s", "CAN Test Packet");
    /* 4. Set packet length */
    packet->length = i;
    /* 5. Send packet */
    uint8_t prio = CSP_PRIO_NORM;
    uint16_t dest = 0;
    uint8_t dport = 0;
    uint8_t src_port = 0;
    uint32_t opts = CSP_SO_NONE;
    csp_dbg_errno = 0;
    csp_sendto(prio, dest, dport, src_port, opts, packet);
    if (csp_dbg_errno != 0) {
        csp_print("csp_sendto() failed with csp_dbg_errno=%u\n", csp_dbg_errno);
    }
    return 0;
}
```

**Comment by yashi** [comment]
You need to open the device and add an interface to it by calling `csp_can_socketcan_open_and_add_interface()`.

https://github.com/libcsp/libcsp/blob/ff53d3c59786a6deef534c3e53cd44bb0a9bf012/examples/csp_server_client.c#L227

I wasn't aware of the wiki.  I'll find time to fix it.  Thanks.

**Comment by yashi** [comment]
```
Last updated on Dec 2, 2011
```
Wow.  More than a decade ago.  That _is_ outdated.

**Comment by Buzzzz** [comment]
Thanks, I am now able to send a connection-less message with csp_sendto() and see it with candump.
Now I want to receive it on the other end with csp_recvfrom(). I cannot find an example using csp_recvfrom and the doxygen documentation says to use a csp_socket_t as the first argument, but I am not sure how to initialize and use it.
This is the code so far, but it segfaults somewhere in csp_recvfrom():

```
void rx(void) {
    // main has called csp_init() and added the CAN interface.
    csp_socket_t sock = { 0 };
    sock.opts = CSP_SO_CONN_LESS;

     // Some magic here to use a connection-less socket with csp_recvfrom().

    for (;;) {
        csp_packet_t *packet = csp_recvfrom(&sock, CSP_MAX_TIMEOUT);
        if (packet != NULL) {
            // print_packet(packet);
            csp_buffer_free(packet);
        }
        else {
            csp_print("csp_recvfrom() failed or timed out\n");
        }
    }
} 
```

**Comment by johandc** [comment]
There are two ways of receiving that packet on a connection less interface:
1. Register a callback with csp_bind_callback() this will just give you the incoming packet directly.
2. You need to manually create a socket by allocating csp_socket_t and setting flags == CSP_SO_CONN_LESS, as you have already done. The magic you are missing is csp_bind() with the port number (Remember this has to be below the MAX_BIND_PORT).

**Comment by Zosoworld** [comment]
> Thanks, I am now able to send a connection-less message with csp_sendto() and see it with candump. Now I want to receive it on the other end with csp_recvfrom(). I cannot find an example using csp_recvfrom and the doxygen documentation says to use a csp_socket_t as the first argument, but I am not sure how to initialize and use it. This is the code so far, but it segfaults somewhere in csp_recvfrom():
> 
> ```
> void rx(void) {
>     // main has called csp_init() and added the CAN interface.
>     csp_socket_t sock = { 0 };
>     sock.opts = CSP_SO_CONN_LESS;
> 
>      // Some magic here to use a connection-less socket with csp_recvfrom().
> 
>     for (;;) {
>         csp_packet_t *packet = csp_recvfrom(&sock, CSP_MAX_TIMEOUT);
>         if (packet != NULL) {
>             // print_packet(packet);
>             csp_buffer_free(packet);
>         }
>         else {
>             csp_print("csp_recvfrom() failed or timed out\n");
>         }
>     }
> } 
> ```

I've managed to avoid the segfault by initializing the rx_queue in the socket as done in the example in [csp_arch.c](https://github.com/libcsp/libcsp/blob/develop/examples/csp_arch.c):
```cpp
csp_static_queue_t sq;
csp_queue_handle_t q;
char buf[3 * sizeof(int16_t)];

q = csp_queue_create_static(3, sizeof(int16_t), buf, &sq);
csp_socket_t sock = {.rx_queue = q};
sock.opts = CSP_SO_CONN_LESS;
```
But even though packets are being sent, I am not receiving them with this code:
```cpp
    int error = csp_can_socketcan_open_and_add_interface("vcan0", CSP_IF_CAN_DEFAULT_NAME, 0, true, &default_iface);
    csp_static_queue_t sq;
    csp_queue_handle_t q;
    char buf[3 * sizeof(int16_t)];

    q = csp_queue_create_static(3, sizeof(int16_t), buf, &sq);
    csp_socket_t sock = {.rx_queue = q};
    sock.opts = CSP_SO_CONN_LESS;
    csp_bind(&sock, 22);
    while (true)
    {
        csp_packet_t *pkt = csp_recvfrom(&sock, 100);
        if (pkt != NULL)
        {
            // print
            csp_buffer_free(pkt);
        }
        else
        {
            // No packet
        }
    }
```

**Comment by johandc** [comment]
csp_listen() creates the rx queue. 
I believe everything you do is correct. So it must be an issue with the router, that packets are not sent to your socket.

Try opening csp route function and add some debug down the way up until you see the packet is queued up for the socket. To figure out why it is not arriving.

**Comment by yashi** [comment]
#728 should tell you how to send a packet via socketcan. Closing.
