### ISSUE TITLE
Fix or remove outdated wiki

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#443]
We have [wiki pages](https://github.com/libcsp/libcsp/wiki) on this GitHub repository, but they are not being maintained. This lack of maintenance has been causing confusion among users (#442).

We also have documents located under the [`doc/`](https://github.com/libcsp/libcsp/tree/develop/doc) directory, and GitHub effectively renders the Markdown format. While the wiki is user-friendly for creating content, it can be challenging to maintain since it's not version-controlled (?) using Git. Therefore, I would suggest considering its removal if there's no one willing to take on its maintenance.

**Comment by johandc** [comment]
Wiki removed
