### ISSUE TITLE
csp_init() hangs up in csp_malloc()

### ISSUE THREAD

**Issue by hernaangq** [libcsp/libcsp#485]
Hello,
I am trying to develop csp(v1.6) software on FreeRTOS on a EFM32GG11 Giant Gecko STK, I already have built libcsp and linked it up to a project and functions such as csp_log_info() work. 
The problem comes when I try to use csp_init which hangs up in csp_malloc and I see this error (ERROR: FreeRTOS maximum used priority is unreasonably big, not proceeding), I have the following code in my main function (I read that csp has to be initialise in main function inside a freertos thread)

```
/* Init CSP with address and default settings */
uint8_t address = 1;
  csp_log_info("Initialising CSP");

      csp_conf_t csp_conf;
      csp_conf_get_defaults(&csp_conf);
      csp_conf.address = address;
      volatile int error;
      error = csp_init(&csp_conf);
      if (error != CSP_ERR_NONE) {
          csp_log_error("csp_init() failed, error: %d", error);
          exit(1);
      }
      csp_log_info("Initialising CSP OK");

```
(I use volatile on csp_init in order to see the value returned when debugging)

Thanks in advance,
Hernán

**Comment by hernaangq** [comment]
btw I´m using csp_server_client example from csp(v1.6) for advice

**Comment by yashi** [comment]
I don't use FreeRTOS at all. So this comment might be way off.  Anyway,

- What is your `configTOTAL_HEAP_SIZE`?
- Which implementation of malloc are you using? There are a few heap implementations under `freertos/portable/MemMang`.
- Can you successfully call `malloc()` alone before calling `csp_init()` with the same size `csp_init()` pass to `malloc()`?
- Do you mind sharing your project to help other FreeRTOS users?

**Comment by secureshadow** [comment]
@hernaangq I would be interested in knowing how you managed to implement freeRTOS and libcsp for your ARM Cortex-M4 MCU. I am struggling to make it for an ARM Cortex M0+ board.
I hope you can share it. Thanks!

**Comment by hernaangq** [comment]
Let me answer your questions.

> I don't use FreeRTOS at all. So this comment might be way off. Anyway,
> 
> * What is your `configTOTAL_HEAP_SIZE`?

```c
#define SL_HEAP_SIZE   2048  /* sl_memory_config.h */
#define configTOTAL_HEAP_SIZE  819  /* FreeRTOSConfig.h */
```
I have those two, which is the minimum HEAP size needed for csp??

> * Which implementation of malloc are you using? There are a few heap implementations under `freertos/portable/MemMang`.

I am using heap_4.c

> * Can you successfully call `malloc()` alone before calling `csp_init()` with the same size `csp_init()` pass to `malloc()`?

No, I can't

**Comment by hernaangq** [comment]
> @hernaangq I would be interested in knowing how you managed to implement freeRTOS and libcsp for your ARM Cortex-M4 MCU. I am struggling to make it for an ARM Cortex M0+ board. I hope you can share it. Thanks!

Try this repository [https://github.com/libcsp/libcsp-freertos](url)

**Comment by secureshadow** [comment]
@hernaangq Yes, I tried, you can see my opened issued here at libcsp for reference. The main problem is that the repository is built for Linux systems with an x86 architecture. To implement it for your cortex M4 ARM MCU, you will need to cross compile it and edit the library to allow support for baremetal architecture like ARM MCUs. Which as far as I understood is not supported. I think it will be better to use ZepyrOS (since I think it is implemented for this OS rather than freeRTOS) but the board I will use in the future it is not supported.

Let me know if you manage to execute libcsp functions inside freeRTOS for your board. I will be interested in seeing your configuration files.

**Comment by yashi** [comment]
> I have those two, which is the minimum HEAP size needed for csp??

You can find out with [`pahole`](https://git.kernel.org/pub/scm/devel/pahole/pahole.git) if you have a compiled binary.

> > * Can you successfully call `malloc()` alone before calling `csp_init()` with the same size `csp_init()` pass to `malloc()`?
> 
> No, I can't

Then, your problem is not libcsp but your FreeRTOS configuration.

**Comment by hernaangq** [comment]
Hello @yashi ,
I can in fact call malloc(0), so the problem does not seem to be in FreeRTOS, it has to be in the configuration of CSP.
Do you specify a HEAP size in your CSP autoconfig?

**Comment by yashi** [comment]
Sure, as you can see from https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/portable/MemMang/heap_4.c#L173

It's basically

```c
void * pvPortMalloc( size_t xWantedSize )
{
    if( xWantedSize > 0 )
    {
        /* allocate */
    }
    else
    {
        mtCOVERAGE_TEST_MARKER();
    }

    vTaskSuspendAll();
    {
        /* If this is the first call to malloc then the heap will require
         * initialisation to setup the list of free blocks. */
    }
}
```

This means it always succeeds when you pass `0`.  Try it with non-`0`.

**Comment by yashi** [comment]
> Do you specify a HEAP size in your CSP autoconfig?


I don't use FreeRTOS at all.

**Comment by yashi** [comment]
It's been a while.  I'm not sure you have fixed it or not but I'm closing this for now.  If you have any more question, please feel free to reopen it. Or open another issue if you have any other problem. Thanks.
