### ISSUE TITLE
Test KISS interface with Linux pty on CI

### ISSUE THREAD

**Issue by yashi** [libcsp/libcsp#490]
It's possible to use KISS interface with Linux pty.

We can do something like

```
socat -d -d -d pty,raw,echo=0 pty,raw,echo=0
./build/examples/csp_server -k /dev/pts/14 -a 2
build/examples/csp_client -k /dev/pts/13 -a 3 -C 2 
```

As you can see from #484, it's better if we have a KISS test in CI.

**Comment by cspuart** [comment]
This worked for me also. I tested it on VMware Ubuntu 18.04.6.
