### ISSUE TITLE
Using the CSP on an Arduino SAMD21 board using FreeRTOS 

### ISSUE THREAD

**Issue by curat97** [libcsp/libcsp#496]
Hello there, I am almostly completely new to the CSP, so it could be that part of my question or the entire question doesn't make sense. Basically I would like to implement the CSP on the Adafruit Feather M0 WiFi w/ATWINC1500 board that is programmable using the Arduino IDE. My first idea to do so is to use the FreeRTOS operating system that can be built on the Arduino SAMD21 board thanks to this library https://github.com/BriscoeTech/Arduino-FreeRTOS-SAMD21 . I have successfully run the examples of the libraries on the board. The next step would be to build libcsp against FreeRTOS running on the board, but at this point I am completely lost on how to do it. Do you have any suggestion? Thanks for your help

**Comment by yashi** [comment]
That's our one of the biggest problems right now.  Nobody, including me, has provided a complete how to for integrating libcsp with FreeRTOS.

#481 has some ideas I know about, but as I wrote in the issue, I don't use FreeRTOS at all.

If you are OK to use Zephyr RTOS instead, here is how to build with libcsp for [`adafruit_trinket_m0`](https://docs.zephyrproject.org/latest/boards/arm/adafruit_feather_m0_basic_proto/doc/index.html)

```
west init -l app
west update
west build -b adafruit_feather_m0_basic_proto
```

Please read https://docs.zephyrproject.org/latest/develop/getting_started/index.html for more detail.

And the code.
```diff
diff --git a/.gitignore b/.gitignore
new file mode 100644
index 0000000..5975d97
--- /dev/null
+++ b/.gitignore
@@ -0,0 +1,2 @@
+*~
+build/
diff --git a/CMakeLists.txt b/CMakeLists.txt
new file mode 100644
index 0000000..ecb7d24
--- /dev/null
+++ b/CMakeLists.txt
@@ -0,0 +1,8 @@
+# SPDX-License-Identifier: Apache-2.0
+
+cmake_minimum_required(VERSION 3.20.0)
+
+find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
+project(hello_world)
+
+target_sources(app PRIVATE src/main.c)
diff --git a/prj.conf b/prj.conf
new file mode 100644
index 0000000..fe7ff31
--- /dev/null
+++ b/prj.conf
@@ -0,0 +1 @@
+CONFIG_LIBCSP=y
diff --git a/src/main.c b/src/main.c
new file mode 100644
index 0000000..7667caf
--- /dev/null
+++ b/src/main.c
@@ -0,0 +1,11 @@
+#include <stdio.h>
+#include <csp/csp.h>
+
+int main(void)
+{
+	csp_init();
+
+	printf("Hello World! %s\n", CONFIG_BOARD);
+
+	return 0;
+}
diff --git a/west.yml b/west.yml
new file mode 100644
index 0000000..48626a9
--- /dev/null
+++ b/west.yml
@@ -0,0 +1,17 @@
+manifest:
+
+  projects:
+    - name: zephyr
+      url: https://github.com/zephyrproject-rtos/zephyr
+      revision: main
+      path: zephyr
+      west-commands: scripts/west-commands.yml
+      import:
+        name-allowlist:
+          - cmsis
+          - hal_atmel
+
+    - name: libcsp
+      url: https://github.com/libcsp/libcsp
+      revision: develop
+      path: modules/lib/libcsp
```

**Comment by curat97** [comment]
Thank you for your fast reply. I have no personal preference towards using freeRTOS or Zephyr RTOS since I'm new to both languages and the learning curve would be similar for both. However, in my project I need to use CSP together with a bunch of other functionalities that are realized using different Arduino libraries (for istance Accelstepper to control stepper motors, WiFi101 to communicate via WiFi). The advantage of the BriscoeTech library is that I can use it as any library on Arduino, together with the other ones. For what concerns the Zephyr OS instead, as far as I know Arduino libraries are not supported in general, even if some effort has been done in that direction (https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core). I guess one way forward could be the one of building the Zephyr OS on my board as you suggested and obtain the same functionalities I obtain at the moment using Arduino libraries by using Zephyr modules. Before embarking in such a journey however I would like to explore all possibilities

**Comment by yashi** [comment]
I'm closing this for now.  If you have more question / commnets, please reopen it.
