### ISSUE TITLE
New Project: What Version to use?

### ISSUE THREAD

**Issue by dietelTiMaMi** [libcsp/libcsp#498]
@yashi @johandc 
In our new project we are going to integrate devices using csp. What version or branch of libcsp would you recommend as the most stable and up to date for new projects at the moment?

**Comment by yashi** [comment]
Depends.
- If you are OK with an unstable API, use `develop`. With `develop`, it's easier, at least for me, to help you when you have some issues. If you are using Zephyr RTOS, `develop` is what you want.
- If you don't need any new features but stable APIs, use `libcsp-2-0` or `libcsp-1`. I don't use them, and I don't spend much time with them, but they are supposed to work.

**Comment by yashi** [comment]
reopen it if you need any more info.
