### ISSUE TITLE
Update Python bindings to use a generator

### ISSUE THREAD

**Issue by jledet** [libcsp/libcsp#5]
The current Python bindings requires manual update every time the API changes. Because we're lazy, we should change to something like pybindgen instead.

**Comment by jledet** [comment]
Pybindgen is here https://launchpad.net/pybindgen
Unfortunately, the project seems to be unmaintained. Last update in 2010.

**Comment by johandc** [comment]
There is a new project called Ctypesgen which i have sucessfully tested.

However there is an issue with packed structures not getting the __packed = 1 attribute set. However a bugreport is already assigned upstream.

**Comment by johandc** [comment]
I have added a script based on ctypesgen but it does not support the packed attribute, which needs to be added manually. Given the fact that there is no known and maintained bindings generator that works 100%, i'm closing this issue for now.
