### ISSUE TITLE
KISS for Zephyr

### ISSUE THREAD

**Issue by ignacio-gr** [libcsp/libcsp#512]
I've got an application that is currently running zephyr on a MCU and needs CSP KISS over USART to work.
Any clue on how to implement it?

**Comment by yashi** [comment]
We are working on it for our project https://github.com/spacecubics/scsat1-rpi.
Stay tuned.

If you can't wait for it, what you have to do is to create a new layer, `libcsp/src/drivers/usart/usart_zephyr.c`, which binds Zephyr UART driver and the libcsp kiss interface layer, `libcsp/src/interfaces/csp_if_kiss.c`
