### ISSUE TITLE
csp_bridge: potential issue in csp_bridge_work()

### ISSUE THREAD

**Issue by dimitrovand** [libcsp/libcsp#526]
In `csp_bridge_work(void)` the following piece of code decides which interface is to be used:
```
	csp_iface_t * destif;
	if (input.iface == bif_a) {
		destif = bif_b;
	} else {
		destif = bif_a;
	}
```
If `csp_bridge_set_interfaces()` hasn't been called by the user, or simply called with invalid parameters, before invoking `csp_bridge_work(void)` this might lead to `csp_send_direct_iface()` being called with an invalid `destif` parameter. `csp_send_direct_iface()` doesn't perform any checks on the validity of its inputs parameters and this could lead to a crash when `iface->nexthop` is invoked from within the function.

**Comment by pr0me** [comment]
suggested a patch in #542

**Comment by yashi** [comment]
@dimitrovand, reopen this if you still have any problem.  Thanks.
