### ISSUE TITLE
Warning socket connection queue full

### ISSUE THREAD

**Issue by hernaangq** [libcsp/libcsp#578]
Hello, 
I am currently trying to make a CSP server on the port number 8, where I am sending messages every 6 seconds.
The problem is that I get the following warning after the 4 CAN message:

![image](https://github.com/libcsp/libcsp/assets/65247229/a21710b6-9381-420a-b539-2a9783b222bb)

I believe it is a configuration problem, but I am not sure: 

```
// CSP init
    Uint8_t address = 2;
    csp_conf_t csp_conf;
    csp_conf_get_defaults(&csp_conf);
    csp_conf.address = address;
    csp_conf.conn_max = CSP_CONN_MAX;    //6
    csp_conf.buffer_data_size = CSP_BUFFER_DATA_SIZE;  //256
    csp_conf.buffers = CSP_NUM_BUFFERS;    //30 
    csp_conf.conn_queue_length = CSP_CONN_QUEUE_LENGTH;   //30
```

I need help with this.

Best regards,
Hernan

**Comment by moonlight83340** [comment]
Hi,
I checked the 1.4 source code, and I'm seeing your warning coming from here :
https://github.com/libcsp/libcsp/blob/v1.4/src/transport/csp_udp.c#L38
So maybe too much connection with that speed ? I don't know yet.

Could you past your code here or on gist ?

You have a warning but are you able to received all the sent messages ?
You could try to test with loop with only 10 messages first and verify if you are able to received the 10 messages, you have sent.

Hope I can help you.

**Comment by hernaangq** [comment]
Hello, thanks for the response:

My server looks like this:

```
    csp_conn_t *conn;
    csp_packet_t *packet;
    csp_socket_t *socket = csp_socket(CSP_SO_NONE);
    csp_bind(socket, 8);
    csp_listen(socket, CSP_BACKLOG_QUEUE_LENGTH);

    while (1)
    {
        conn = csp_accept(socket, CSP_MAX_DELAY);

        if (conn == NULL)
        {
            debug_printf_safe(ERROR, "Connection failed");
            continue;
        }

        while ((packet = csp_read(conn, CSP_MAX_TIMEOUT)) != NULL)
        {
            if (packet==NULL){
                debug_printf_safe(ERROR, "Packet is NULL");
                break;
            }
            
            switch (csp_conn_dport(conn))
            {
            case 8:
                debug_printf_safe(INFO, "Received packet from port 8");
                csp_buffer_free(packet);
                break;
            
            }

        }

        csp_close(conn);

    }
```

It looks like the socket buffer is getting full because there is nothing freeing it. Am I using correctly csp_buffer_free?

Also, my CAN velocity is 250kbps maybe that is too high? Should I lower it? 

The CAN thread is receiving all packets correctly though.
Here is the code for that:


```
CANMsg_t CANRXmsg;
    int errorCSP = CSP_ERR_NONE;
    csp_iface_t *EJ = csp_can_obc_get_interface();
    for (;;) {
        // suspend task, waiting for can packet to arrive in queue
        if (pdTRUE == xQueueReceive(CANQueueHandle, &CANRXmsg, portMAX_DELAY)) {
            // PROCESS CAN PACKET
            //debug_printf_safe(INFO, "RECEIVED CAN PACKET: %s", (const char *)CANRXmsg.u8_data);
            if (CANRXmsg.u8_dlc > 0){
                errorCSP = csp_can_rx(EJ, CANRXmsg.u32_canId, CANRXmsg.u8_data, CANRXmsg.u8_dlc, NULL);
                

                if (errorCSP != CSP_ERR_NONE)
                {
                    debug_printf_safe(ERROR, "CSP CAN RX ERROR %d", errorCSP);
                }
            }

        }
    }
```

**Comment by moonlight83340** [comment]
> Hello, thanks for the response:
> 
> My server looks like this:
> 
> ```
>     csp_conn_t *conn;
>     csp_packet_t *packet;
>     csp_socket_t *socket = csp_socket(CSP_SO_NONE);
>     csp_bind(socket, 8);
>     csp_listen(socket, CSP_BACKLOG_QUEUE_LENGTH);
> 
>     while (1)
>     {
>         conn = csp_accept(socket, CSP_MAX_DELAY);
> 
>         if (conn == NULL)
>         {
>             debug_printf_safe(ERROR, "Connection failed");
>             continue;
>         }
> 
>         while ((packet = csp_read(conn, CSP_MAX_TIMEOUT)) != NULL)
>         {
>             if (packet==NULL){
>                 debug_printf_safe(ERROR, "Packet is NULL");
>                 break;
>             }
>             
>             switch (csp_conn_dport(conn))
>             {
>             case 8:
>                 debug_printf_safe(INFO, "Received packet from port 8");
>                 csp_buffer_free(packet);
>                 break;
>             
>             }
> 
>         }
> 
>         csp_close(conn);
> 
>     }
> ```
> 
> It looks like the socket buffer is getting full because there is nothing freeing it. Am I using correctly csp_buffer_free?
> 
> Also, my CAN velocity is 250kbps maybe that is too high? Should I lower it?
> 
> The CAN thread is receiving all packets correctly though. Here is the code for that:
> 
> ```
> CANMsg_t CANRXmsg;
>     int errorCSP = CSP_ERR_NONE;
>     csp_iface_t *EJ = csp_can_obc_get_interface();
>     for (;;) {
>         // suspend task, waiting for can packet to arrive in queue
>         if (pdTRUE == xQueueReceive(CANQueueHandle, &CANRXmsg, portMAX_DELAY)) {
>             // PROCESS CAN PACKET
>             //debug_printf_safe(INFO, "RECEIVED CAN PACKET: %s", (const char *)CANRXmsg.u8_data);
>             if (CANRXmsg.u8_dlc > 0){
>                 errorCSP = csp_can_rx(EJ, CANRXmsg.u32_canId, CANRXmsg.u8_data, CANRXmsg.u8_dlc, NULL);
>                 
> 
>                 if (errorCSP != CSP_ERR_NONE)
>                 {
>                     debug_printf_safe(ERROR, "CSP CAN RX ERROR %d", errorCSP);
>                 }
>             }
> 
>         }
>     }
> ```

Hi, 
Sorry I didn't have the time to test the can my self.µ

> 
It looks like the socket buffer is getting full because there is nothing freeing it. Am I using correctly csp_buffer_free?
I don't think the problem is because the socket isn't free.
Maybe you create too much connections in a small laps of time. But I'm unsure of that.. 

Can I ask you the full code of your client part ?

**Comment by hernaangq** [comment]
Hello, of course yo can ask ! Here it is:


```
/* Prepare data */
	csp_packet_t * packet = csp_buffer_get(5);
	if (packet == NULL)
		return;

	/* Open connection */
	csp_conn_t * conn = csp_connect(CSP_PRIO_NORM, node, 5, 0, CSP_O_NOCRC32);
	if (conn == NULL) {
		csp_buffer_free(packet);
		return;
	}

	//packet->data[0] = 0x77;
	//packet->data[1] = 0x6F;
	//packet->data[2] = 0x72;
	//packet->data[3] = 0x6c;
	//packet->data[4] = 0x64;


	packet->data[0] = 0x68;
	packet->data[1] = 0x65;
	packet->data[2] = 0x6c;
	packet->data[3] = 0x6c;
	packet->data[4] = 0x6f;
	packet->data[5] = 0x20;
	packet->data[6] = 0x63;
	packet->data[7] = 0x75;
	packet->data[8] = 0x62;
	packet->data[9] = 0x65;



	packet->length = 10;

	//printf(" %u.\r\n", packet->data);
	printf("Sending: %s\n", (char *)packet->data);

	/* Try to send frame */
	if (!csp_send(conn, packet, 0))
		csp_buffer_free(packet);

	csp_close(conn);
```

After debugging in the server, I found out the porgram never gets into the csp_close(conn). I tried to put the csp_close right below the csp_buffer_free(packet) in the server code, but it dies in csp_close.

**Comment by moonlight83340** [comment]
> Hello, of course yo can ask ! Here it is:
> 
> ```
> /* Prepare data */
> 	csp_packet_t * packet = csp_buffer_get(5);
> 	if (packet == NULL)
> 		return;
> 
> 	/* Open connection */
> 	csp_conn_t * conn = csp_connect(CSP_PRIO_NORM, node, 5, 0, CSP_O_NOCRC32);
> 	if (conn == NULL) {
> 		csp_buffer_free(packet);
> 		return;
> 	}
> 
> 	//packet->data[0] = 0x77;
> 	//packet->data[1] = 0x6F;
> 	//packet->data[2] = 0x72;
> 	//packet->data[3] = 0x6c;
> 	//packet->data[4] = 0x64;
> 
> 
> 	packet->data[0] = 0x68;
> 	packet->data[1] = 0x65;
> 	packet->data[2] = 0x6c;
> 	packet->data[3] = 0x6c;
> 	packet->data[4] = 0x6f;
> 	packet->data[5] = 0x20;
> 	packet->data[6] = 0x63;
> 	packet->data[7] = 0x75;
> 	packet->data[8] = 0x62;
> 	packet->data[9] = 0x65;
> 
> 
> 
> 	packet->length = 10;
> 
> 	//printf(" %u.\r\n", packet->data);
> 	printf("Sending: %s\n", (char *)packet->data);
> 
> 	/* Try to send frame */
> 	if (!csp_send(conn, packet, 0))
> 		csp_buffer_free(packet);
> 
> 	csp_close(conn);
> ```
> 
> After debugging in the server, I found out the porgram never gets into the csp_close(conn). I tried to put the csp_close right below the csp_buffer_free(packet) in the server code, but it dies in csp_close.

I'm really unsure about your issue. Could you send here by zip the source code ? 😅 
I will try to get a time slot to test myself and tell you what I'm getting.
You have a server in 1.6 and client in 1.4 ?

**Comment by hernaangq** [comment]
I am sorry, I can't send you more code than that because the rest is private in my company.
Both server and client in v1.6.

Is is possible that my server code is wrong?? Do you have anymore examples I could try?

Client side works perfectly, I can assure that after debugging it.



 
> 
> Maybe you create too much connections in a small laps of time. But I'm unsure of that..
> 
> 

What do you mean with this? Is there any limit in making connections?

**Comment by yashi** [comment]
> After debugging in the server, I found out the porgram never gets into the csp_close(conn).

Do you know why?

**Comment by hernaangq** [comment]
Because of this part of the code:


`while ((packet = csp_read(conn, CSP_MAX_TIMEOUT)) != NULL)`



And a question about the client: 

Should I open and close a connection each time I send a packet?

**Comment by yashi** [comment]
> Because of this part of the code:
> 
> `while ((packet = csp_read(conn, CSP_MAX_TIMEOUT)) != NULL)`

can you explain using words?

> And a question about the client:
> 
> Should I open and close a connection each time I send a packet?

depends.

**Comment by hernaangq** [comment]
depends on what?

**Comment by yashi** [comment]
Your design?

You don't need to open and close a connection each time.  But you can.  The current code under `examples/` might not be ideal, say, for CSP RDP. It has been like that for a long time and that's what we have right now.

**Comment by yashi** [comment]
> I can't send you more code than that because the rest is private in my company.

Without a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example), it's hard to tell what's going on. If you got a MRE, please reopen it. Thanks.
