### ISSUE TITLE
Why my client can't ping to server

### ISSUE THREAD

**Issue by poomravint** [libcsp/libcsp#608]
I am coding two function client() and server() then use pthread to call those functions
Client() will ping to the server but everytime client will get -1 ms 
![image](https://github.com/libcsp/libcsp/assets/101710514/cdf6513e-d41e-43a3-ac95-dc3117be8b82)
I don't understand what's point did i do wrong

This is my zip code : 
[csp_re_sen.zip](https://github.com/user-attachments/files/16137674/csp_re_sen.zip)
I set address like this  :
![image](https://github.com/libcsp/libcsp/assets/101710514/c6a50b5d-36f2-4bf1-884e-8cb29b9ca64a)
I think it's my first mistake but I don't know how to set address.
Someone please help me I have been coding this code for 1 month and now It still not working.

**Comment by yashi** [comment]
Do the examples on https://github.com/libcsp/libcsp/issues/606#issuecomment-2212402351 help?

**Comment by poomravint** [comment]
> Do the examples on [#606 (comment)](https://github.com/libcsp/libcsp/issues/606#issuecomment-2212402351) help?

Thanks a lolt your examples can help me very much.

**Comment by yashi** [comment]
Glad to hear that. Repen this or open new one if you have more question. Closing.
