### ISSUE TITLE
Support multiple instances of interfaces

### ISSUE THREAD

**Issue by jledet** [libcsp/libcsp#61]
We generally only support a single instance of each interface type, e.g. only one CAN interface because the csp_iface_t structs are statically defined. The KISS interface has some code to support multiple UARTs, but it would be nice to generalize this to cover all interface types. It should be possible to have both multiple instances of the same type (e.g. two SocketCAN interfaces) and of the same type but with different drivers (e.g. a platform I2C controller and an external controller).

**Comment by johandc** [comment]
We now have a design guideline for this see pull-request #90

**Comment by johandc** [comment]
Fixed in #90
