### ISSUE TITLE
Multiple nodes in a single process

### ISSUE THREAD

**Issue by lu-maca** [libcsp/libcsp#610]
Hi all,

I'm quite sure about the answer, but asking is free: is there a way (maybe another implementation of libcsp) to instantiate more than one CSP node in a single process? I'm using csp 1.4.

Basically I'd like to do something like:
```c
csp_init(1); // first instance 
csp_init(2); // second instance
// ...
```

A use case would be having a single process with multiple servers each with a given node

Thanks,
Luca

**Comment by yashi** [comment]
That's not possible with the current implementation.

**Comment by lu-maca** [comment]
As I thought, thanks!
