### ISSUE TITLE
How to use csp_cmp_ident

### ISSUE THREAD

**Issue by moonlight83340** [libcsp/libcsp#611]
**Brief**
I'm trying to use `csp_cmp_ident`, but I'm not sure if I'm using it correctly.

I was looking at a previous issue: https://github.com/libcsp/libcsp/issues/513. 
There was a strange problem with a Python example. 
I'm experiencing the same error, so I started debugging, and it seems like the issue originates from `csp_cmp_ident`. 
Therefore, I decided to test it using a C example.

**Current Understanding**
I'm unsure if I'm using `csp_cmp_ident` correctly.

**Expected Behavior**
`csp_cmp_ident` should work without errors.

**Impact**
I'm unable to determine if `csp_cmp_ident` is functioning properly or if I'm making a mistake.

I've added some code to the current development example to test `csp_cmp_ident`. I am using the zmq interface.

```
	struct csp_cmp_message ident_msg;
	memset(&ident_msg, 0, sizeof(ident_msg));
	int res;
	res = csp_cmp_ident(server_address,1000,&ident_msg);
	csp_print("csp_cmp_ident server_address : %d\n",server_address);
	csp_print("csp_cmp_ident res : %d\n",res);
	if(res == CSP_ERR_NONE){
		csp_print("csp_cmp_ident OK\n");
	}else if(res == CSP_ERR_NOMEM){
		csp_print("csp_cmp_ident CSP_ERR_NOMEM\n");
		return -1;
	}else if(res == CSP_ERR_INVAL){
		csp_print("csp_cmp_ident CSP_ERR_INVAL\n");
		return -1;
	}else if(res == CSP_ERR_TIMEDOUT){
		csp_print("csp_cmp_ident CSP_ERR_TIMEOUT\n");
		return -1;
	}
```

**Comment by yashi** [comment]
Make sure to set these parameters in _server side_.

```c
	csp_conf.hostname = "foo";
	csp_conf.model = "My Spacecraft";
	csp_conf.revision = "v1000";
```

Then, you can use `csp_cmp_ident()` in your client side:

```c
	struct csp_cmp_message msg;
	memset(&msg, 0, sizeof(msg));
	csp_cmp_ident(SERVER_ADDR, 1000, &msg);
	printf("hostname: %s\n", msg.ident.hostname);
	printf("model: %s\n", msg.ident.model);
	printf("revision: %s\n", msg.ident.revision);
	printf("date: %s\n", msg.ident.date);
	printf("time: %s\n", msg.ident.time);
```
