### ISSUE TITLE
How to use CSP to CAN??

### ISSUE THREAD

**Issue by ghost** [libcsp/libcsp#629]
I am currently using CSP version 1.6 on Ubuntu 18.04 LTS. I am working with GomSpace's A3200 and would like to send and receive messages with other devices using CAN communication. However, no matter how much I look into it, I cannot figure out which code to use.

I referred to [this issue on GitHub](https://github.com/libcsp/libcsp/issues/442) and wrote a function, but I encountered the following error: - I tried various attempts to reference csp_can_socketcan_open_and_add_interface, but I failed.

![CAN ERROR](https://github.com/user-attachments/assets/d1e94b4c-34be-4044-a78d-8c94a45e214a)

Is it possible that socketcan cannot be used on the A3200?

Are there any third-party resources or documentation regarding CAN transmission with CSP that I could refer to?
I apologize for my questions not being very specific, as I am a beginner.

**Comment by dimitrovand** [comment]
Hello @Elowehye, are you building an application for Ubuntu or GomSpace's A3200? If your code is meant to run on GomSpace's A3200 and it’s not running Linux, you won’t be able to use socketcan. I’m not sure if there’s any detailed documentation on this, but you can refer to the source code here: https://github.com/libcsp/libcsp/blob/v1.6/src/drivers/can/can_socketcan.c, which demonstrates how to add a CAN driver to the existing CAN interface.

**Comment by ghost** [comment]
Hello @dimitrovand,
This code was intended to run on GomSpace's A3200. Since the A3200 uses FreeRTOS, I won’t be able to use socketcan. However, I'll need to look into GomSpace's code that serves a similar purpose. Thanks for the hint!

In the CSP system, aside from the reference at https://github.com/libcsp/libcsp/issues/442, are there any other specific code references related to CAN transmission that I should be aware of?
