### ISSUE TITLE
Request: Add policy of how v1 vs. v2/develop lineage works

### ISSUE THREAD

**Issue by parker-research** [libcsp/libcsp#652]
## Description

We're using v1 in a project, and are making some contributions to the `libcsp-1` lineage branch. Is there a stable way to make these changes and roll them forward into v2 as well (somehow, maybe a merge commit from the feature branch), or is the plan to make changes (e.g., global find-and-replace for `__FUNCTION__` to `__func__`) separately in parallel in the `develop` branch?

**Comment by yashi** [comment]
If you find the same issue in the `develop` branch, please fix it there first. Then, we can backport it if possible. If backporting is not straightforward, I will need to ask the authors to make it work.

If needed, we can create dedicated lables for backporting.
