### ISSUE TITLE
python: python binding example failed to connect on libcsp-2-0 branch

### ISSUE THREAD

**Issue by moonlight83340** [libcsp/libcsp#664]
## Description

I'm currently having an error when trying to test python binding on libcsp-2-0 branch.
csp_cmp_ident failed with error `-3` .

## Steps to Reproduce

1. Build libcsp and build libcsp python binding
2. Then run `build/examples/zmqproxy `
3. Then `PYTHONPATH=builddir python3 examples/python_bindings_example_server.py` 
4. Then `PYTHONPATH=builddir python3 examples/python_bindings_example_client.py -z localhost -s 27 -a 2`

## Expected behavior

I expected the python binding work with no error.

## Actual Behavior:

csp_cmp_ident failed with error `-3` .
See log.

## Environment Details:

Provide information about your environment, including:

- Build OS:  Ubuntu 22.04
- Target OS: Ubuntu 22.04
- libcsp commit hash: 87f205b30d9a05dcf9afb0bfd50975a77ce3761a
- Meson version: 0.53.2-2ubuntu2
- Ninja version: 1.10.0-1build1

## Logs or console output from the very beginning to the end

```
 build/examples/zmqproxy &
  PYTHONPATH=builddir python3 examples/python_bindings_example_server.py &
  PYTHONPATH=builddir python3 examples/python_bindings_example_client.py -z localhost -s 27 -a 2
  pkill zmqproxy
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.9/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.9/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.9/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.9/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.9/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.9/x64/lib
Traceback (most recent call last):
  File "/home/runner/work/libcsp/libcsp/examples/python_bindings_example_client.py", line 79, in <module>
Connections:
    print("CMP ident:", libcsp.cmp_ident(options.server_address))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
csp.Error: csp_cmp_ident(), result/error: -3
Routes:
[00 0x7fc15c294c20] S:0, 0 -> 0, 0 -> 0 (17) fl 0
[01 0x7fc15c294d30] S:0, 0 -> 0, 0 -> 0 (18) fl 0
[02 0x7fc15c294e40] S:0, 0 -> 0, 0 -> 0 (19) fl 0
[03 0x7fc15c294f50] S:0, 0 -> 0, 0 -> 0 (20) fl 0
[04 0x7fc15c295060] S:0, 0 -> 0, 0 -> 0 (21) fl 0
[05 0x7fc15c295170] S:0, 0 -> 0, 0 -> 0 (22) fl 0
[06 0x7fc15c295280] S:0, 0 -> 0, 0 -> 0 (23) fl 0
[07 0x7fc15c295390] S:0, 0 -> 0, 0 -> 0 (24) fl 0
0/14 LOOP
0/0 ZMQHUB
/home/runner/work/_temp/a82b0407-2e04-4c99-9e83-85574cfb2d7d.sh: line 3:  4367 Floating point exception(core dumped) PYTHONPATH=builddir python3 examples/python_bindings_example_server.py
Error: Process completed with exit code 1.

```

## Additional Context:

I'm trying to make the python workflow works on libcsp-2-0 branch, and I'm getting an error on csp_cmp_ident().
I think it may be a connection problem between server and client.

Server address is `27` by default.

  `build/examples/zmqproxy `
  `PYTHONPATH=builddir python3 examples/python_bindings_example_server.py` 
  `PYTHONPATH=builddir python3 examples/python_bindings_example_client.py -z localhost -s 27 -a 2`
  
 
  See my modification : https://github.com/moonlight83340/libcsp/commits/libcsp-2-0-python-binding-test-clean/
  
  edit: Client send the packet and proxy seems to received it but server not responding.
  Server take a long time to start.
  
## Checklist

- [x] I've searched in "Issues" for similar issues, both open and closed.
- [x] I've used GitHub Flavored Markdown (GFM) to format my text.
- [x] I've avoided using screenshots for console output or logs
- [x] I've included all relevant details and steps to reproduce the issue.
- [x] I've provided information about my environment.
- [x] I've attached necessary logs or code snippet for minimal reproducible example.

**Comment by yashi** [comment]
Where is the log? It says "Logs or console output from the **_very beginning_** to the end" but you don't have it.

**Comment by moonlight83340** [comment]
Fix by https://github.com/libcsp/libcsp/pull/665
