### ISSUE TITLE
Requirements and Coverage

### ISSUE THREAD

**Issue by perigoso** [libcsp/libcsp#698]
Hello,

I'm investigating the possibility of integrating this library in a professional setting, but we have some requirements that it is not immediately obvious this meets:

- Are there any formal requirements defined?
- Is there any coverage testing/reporting?
- Are there any tests implemented beyond  the workflows in GitHub actions?

Thanks in advance :smiley:

**Comment by yashi** [comment]
Hi @perigoso,

> * Are there any formal requirements defined?

AFAIK, no.

> * Is there any coverage testing/reporting?

no, not in the public.

> * Are there any tests implemented beyond  the workflows in GitHub actions?

no. I've started https://github.com/spacecubics/libcsp-zephyr but progress is slow.

**Comment by yashi** [comment]
Please reopen if you need more info. closing.

**Comment by perigoso** [comment]
Thank you for the info
