### ISSUE TITLE
Proper python bindings

### ISSUE THREAD

**Issue by jledet** [libcsp/libcsp#70]
As correctly pointed out by issue #54, we need a better way of generating the bindings. Something with support for multiple languages would be nice, but python bindings should be our main focus.

**Comment by johandc** [comment]
@perwulff @sorennohr I have marked this as comming in v1.5. From what i've seen in your pr #92 it lookeds pretty solid already. So i was hoping you could make it?

**Comment by perwulff** [comment]
Yes, we are working on it internally and once we are satisfied, it will be pushed.

**Comment by johandc** [comment]
Hi Per,

What's the status on that python module?

**Comment by perwulff** [comment]
It is not ready to be merged into 1.5. Best guess at the moment, is within a month - maybe sooner.

**Comment by smorad** [comment]
Has there been any update with this? Ctypesgen does not work with python3.

**Comment by sorennohr** [comment]
See https://github.com/libcsp/libcsp/pull/112 @smorad
