### ISSUE TITLE
unclear usage of csp_queue_free

### ISSUE THREAD

**Issue by dimitrovand** [libcsp/libcsp#704]
## Description
Going through the code it is unclear to me what is the purpose of the following line:
https://github.com/libcsp/libcsp/blob/4ab49343f53c5b734a0a225e0769cda7955c5781/src/csp_port.c#L156
It is supposed to delete the queue?

**Comment by yashi** [comment]
`csp_socket_close()` was added by #411.  And I missed the `csp_queue_free()` on the static queue. My bad.
We really need test code for all functions.

**Comment by dimitrovand** [comment]
True.. tests are a must.
