### ISSUE TITLE
How to use header in Hmac calculation

### ISSUE THREAD

**Issue by poomravint** [libcsp/libcsp#730]
I try to use header in Hmac calculation by this `csp_hmac_append(packet, true);`
When I run my code I got : `Segmentation fault`.
But when I use `csp_hmac_append(packet, false);`
When I run my code everything is ok.
I saw I need to use csp_id_prepend right ? but I don't know which library that I need to include in my code.
![image](https://github.com/user-attachments/assets/839f2043-c0b2-4d4c-82df-503aad0b1ff3)

**Comment by yashi** [comment]
as always, please post with a [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example). It's hard to see what's going on without it.

**Comment by poomravint** [comment]
Ok I got it , I am so sorry.
This is my code :
![image](https://github.com/user-attachments/assets/bdc17ec1-dde4-4617-99cb-4efe0ebeb943)
and this is my result :
![image](https://github.com/user-attachments/assets/7ed365f8-2e76-4621-ae4e-dc8ad41b7167)

**Comment by yashi** [comment]
please don't use screenshots. Use [gist](https://gist.github.com/).

**Comment by poomravint** [comment]
I am sorry this is my code : <script src="https://gist.github.com/poomravint/807ae77246054ed9344fd939628517f4.js"></script>

**Comment by poomravint** [comment]
Ok This is my code : [https://gist.github.com/poomravint/807ae77246054ed9344fd939628517f4](url)

**Comment by poomravint** [comment]
Ok This is my code : https://gist.github.com/poomravint/807ae77246054ed9344fd939628517f4

**Comment by yashi** [comment]
OK I guess it's my fault. you need to call `csp_id_prepend(packet);` to initialize `frame_begin`. Here is my MRE.

```c
#include <csp/csp.h>
#include <csp/csp_debug.h>
#include <csp/csp_id.h>
#include <csp/crypto/csp_hmac.h>

int main(int argc, char * argv[])
{
	csp_packet_t * packet;

	csp_init();

	packet = csp_buffer_get_always();
	csp_id_prepend(packet);

	csp_hmac_append(packet, true);
	csp_hmac_verify(packet, true);

	return 0;
}
```

**Comment by poomravint** [comment]
Thanks Now I can send but I think my receiver have something wrong because my receiver got the correct data but when I use `printf("HMAC Result %d\n", csp_hmac_verify(req, true));`  then I got :
![image](https://github.com/user-attachments/assets/14e8aadb-7280-4087-97da-7ddc58fdef5d)
but the sender before I send to receiver I got check by `printf("HMAC Result %d\n", csp_hmac_verify(packet, true));`  then I got : 
![image](https://github.com/user-attachments/assets/aad0fbc7-aa13-4313-9517-25c847e184e0)

I will try to fix it with myself and clean my code I think if I show you my code it hard for you to understand my code.
If I can't solve my problem I will ask you again Thanks a lot.

**Comment by yashi** [comment]
Do you know how to use [`gdb`](https://www.gnu.org/savannah-checkouts/gnu/gdb/index.html)? Place a break on `csp_hmac_veify()` to see what's going on. I'm assuming your are running it on Linux.

And please do not use screenshots. You can just copy & paste the charactors on your console to here with triple quotes. Se https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by yashi** [comment]
Please open a new issue when you can't figure it out. I'm closing this for now.

**Comment by poomravint** [comment]
Ok I got it , Thanks again
