### ISSUE TITLE
RTEMS port

### ISSUE THREAD

**Issue by luuke** [libcsp/libcsp#732]
Hello,

Are you aware of any existing port of CSP for RTEMS?
I've been searching, but haven't had any luck finding one.

Best regards,
Łukasz

**Comment by yashi** [comment]
Not that I know of.  Somebody else might know.

It'd be nice to have RTEMS port.

**Comment by luuke** [comment]
Alright.

Then maybe you have a list of code modifications required to make a full port?
Something like:
- add something in CMakeLists
- add something in wscript
- add RTEMS specifics in src/arch
and so on. Just don't want to miss anything.

I don't want to make any promises, but I might give it a try.

**Comment by yashi** [comment]
Porting the code under `src/arch` should be sufficient. You can choose one of the build systems we support (Waf, Meson, CMake), and I can help with the others. Of course, you can port to all three by yourself if you prefer. :smiley: 

One thing I'd like to request is a simple build test. If you’re familiar with GitHub Actions, please write a new action to build against RTEMS. If not, please let us know how to build it, so we can create a GitHub Action for it.

**Comment by yashi** [comment]
I'm closing this for now. Reopen or open new one if you have more questions.
