### ISSUE TITLE
CSP_MAX_DELAY should be CSP_INFINITY

### ISSUE THREAD

**Issue by johandc** [libcsp/libcsp#9]
Use the FreeRTOS function to never timeout if portMAX_DELAY (CSP_MAX_DELAY) is passed to a queue or semaphore.
This is fixed for FreeRTOS, but posix just uses a large number.
Posix should not use a time semaphore if MAX_DELAY is passed.

Finally, CSP_MAX_DELAY could be renamed to CSP_INFINITY in order to prevent confusion, but this is breaking backwards compatability...

**Comment by jledet** [comment]
CSP_INFINITY added in 5844e6f. Arch calls have been updated to wait indefinitely when this value is passed as timeout.
